/*
 * VOrdenPago.java
 *
 * Created on 14 de septiembre de 2007, 09:07
 */

package org.adempiere.webui.apps.form;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;

import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

import org.adempiere.webui.component.Button;
import org.adempiere.webui.component.Checkbox;
import org.adempiere.webui.component.Column;
import org.adempiere.webui.component.Columns;
import org.adempiere.webui.component.Datebox;
import org.adempiere.webui.component.Grid;
import org.adempiere.webui.component.GridFactory;
import org.adempiere.webui.component.Label;
import org.adempiere.webui.component.Row;
import org.adempiere.webui.component.Rows;
import org.adempiere.webui.component.Tab;
import org.adempiere.webui.component.Tabbox;
import org.adempiere.webui.component.Tabpanel;
import org.adempiere.webui.component.Tabpanels;
import org.adempiere.webui.component.Tabs;
import org.adempiere.webui.component.Textbox;
import org.adempiere.webui.editor.WDateEditor;
import org.adempiere.webui.editor.WSearchEditor;
import org.adempiere.webui.editor.WTableDirEditor;
import org.adempiere.webui.event.ValueChangeEvent;
import org.adempiere.webui.event.ValueChangeListener;
import org.adempiere.webui.panel.ADForm;
import org.adempiere.webui.window.FDialog;
import org.openXpertya.apps.form.VComponentsFactory;
import org.openXpertya.apps.form.VModelHelper;
import org.openXpertya.apps.form.VOrdenPago;
import org.openXpertya.apps.form.VOrdenPagoModel;
import org.openXpertya.apps.form.VOrdenPagoModel.MedioPago;
import org.openXpertya.apps.form.VOrdenPagoModel.MedioPagoCheque;
import org.openXpertya.apps.form.VOrdenPagoModel.MedioPagoCredito;
import org.openXpertya.apps.form.VOrdenPagoModel.MedioPagoEfectivo;
import org.openXpertya.apps.form.VOrdenPagoModel.MedioPagoTransferencia;
import org.openXpertya.apps.form.VOrdenPagoModel.ResultItemFactura;
import org.openXpertya.model.Lookup;
import org.openXpertya.model.MBPartner;
import org.openXpertya.model.MCurrency;
import org.openXpertya.model.MLookup;
import org.openXpertya.model.MLookupFactory;
import org.openXpertya.model.MLookupInfo;
import org.openXpertya.model.MSequence;
import org.openXpertya.model.X_C_BankAccountDoc;
import org.openXpertya.util.CLogger;
import org.openXpertya.util.DB;
import org.openXpertya.util.DisplayType;
import org.openXpertya.util.Env;
import org.openXpertya.util.Msg;
import org.zkoss.zk.ui.event.Event;
import org.zkoss.zk.ui.event.EventListener;
import org.zkoss.zk.ui.event.Events;
import org.zkoss.zkex.zul.Borderlayout;
import org.zkoss.zkex.zul.Center;
import org.zkoss.zkex.zul.North;
import org.zkoss.zkex.zul.South;
import org.zkoss.zkmax.zul.Tablechildren;
import org.zkoss.zkmax.zul.Tablelayout;
import org.zkoss.zul.AbstractListModel;
import org.zkoss.zul.Combobox;
import org.zkoss.zul.Div;
import org.zkoss.zul.Hbox;
import org.zkoss.zul.ListModelExt;
import org.zkoss.zul.Panel;
import org.zkoss.zul.Panelchildren;
import org.zkoss.zul.Radio;
import org.zkoss.zul.Radiogroup;
import org.zkoss.zul.RowRenderer;
import org.zkoss.zul.Separator;
import org.zkoss.zul.Space;
import org.zkoss.zul.Tree;
import org.zkoss.zul.Treechildren;
import org.zkoss.zul.Treeitem;

/**
 *
 * @author  usuario
 */
public class WOrdenPago extends ADForm implements ValueChangeListener, TableModelListener /*implements /*FormPanel,ActionListener,TableModelListener,VetoableChangeListener,ChangeListener,TreeModelListener,MouseListener,CellEditorListener,ASyncProcess*/ {

    /** Creates new form WOrdenPago */
    public WOrdenPago() {

    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" C�digo Generado  ">//GEN-BEGIN:initComponents
    
    protected void initComponents() {
    	
        buttonGroup1 = new Radiogroup();
        buttonGroup2 = new Radiogroup();
        
        jPanel1 = GridFactory.newGridLayout();
		
        lblBPartner = new Label();
        lblClient = new Label();
        lblDocumentNo = new Label();
        lblDescription = new Label();
        
        MLookup lookupClient = MLookupFactory.get (Env.getCtx(), m_WindowNo, 0, 1014335, DisplayType.TableDir);
        cboClient = new WTableDirEditor("AD_Client_ID", false, false, true, lookupClient);
        cboClient.setValue(Env.getAD_Client_ID(Env.getCtx()));
        cboClient.setReadWrite(false);
        
        MLookup lookupPartner = MLookupFactory.get (Env.getCtx(), m_WindowNo, 0, 3499, DisplayType.Search);
		BPartnerSel = new WSearchEditor ("C_BPartner_ID", true, false, true, lookupPartner);
		
        fldDocumentNo = new Textbox(); 
        
        lblOrg = new Label();
        MLookup lookupOrg = MLookupFactory.get (Env.getCtx(), m_WindowNo, 0, 1016168, DisplayType.TableDir);
		cboOrg = new WTableDirEditor("AD_Org_ID", false, false, true, lookupOrg);
		cboOrg.setValue(Env.getAD_Org_ID(Env.getCtx()));
		
        radPayTypeStd = new Radio();
        radPayTypeAdv = new Radio();
        radPayTypeStd.setValue("PAGO NORMAL");
        radPayTypeStd.setSelected(true);
        
        txtDescription = new Textbox();

		
		lblDocumentType = new Label();
		// FEDE:TODO: Centralizar la creacion de combos en algun lugar
		MLookupInfo infoDocType = VComponentsFactory.MLookupInfoFactory( Env.getCtx(),m_WindowNo, 0, 1016307, DisplayType.TableDir, m_model.getDocumentTypeSqlValidation());
		MLookup lookupDocType = new MLookup(infoDocType, 0);
		cboDocumentType = new WTableDirEditor("C_DocType_ID", false, false, true, lookupDocType);
		
		tblFacturas = new Grid();
		tblFacturas.setHeight("350px");
		listModel = new FacturasModel(VModelHelper.HideColumnsTableModelFactory(m_model.m_facturasTableModel), m_WindowNo);
		renderer = new GridRenderer(this);
		tblFacturas.setModel(listModel);
		tblFacturas.setRowRenderer(renderer);
		
        txtTotalPagar1 = new Textbox();
//        txtTotalPagar1.setConstraint("/^[0-9]+$/");
        lblTotalPagar1 = new Label();
        
		rInvoiceAll = new Radio();
		rInvoiceDate = new Radio();

        invoiceDatePick = new Datebox();

        cmdEliminar = new Button();
        cmdEditar = new Button();

        cmdGrabar = new Button();

        lblEfectivoLibroCaja = new Label();
        
		MLookupInfo infoLibroCaja = VComponentsFactory.MLookupInfoFactory( Env.getCtx(),m_WindowNo, 0, 5241, DisplayType.Search, m_model.getEfectivoLibroCajaSqlValidation());
		MLookup lookupLibroCaja = new MLookup(infoLibroCaja, 0);
		efectivoLibroCaja = new WSearchEditor("C_Cash_ID", false, false, true, lookupLibroCaja);

        lblEfectivoImporte = new Label();
        txtEfectivoImporte = new Textbox();
        txtEfectivoImporte.setConstraint("/^[0-9]+$/");
        
//        jPanel6 = new javax.swing.JPanel();
          lblTransfCtaBancaria = new Label();
        lblTransfNroTransf = new Label();
        lblTransfImporte = new Label();
        lblTransfFecha = new Label();
        MLookupInfo infoTransf = VComponentsFactory.MLookupInfoFactory(Env.getCtx(),m_WindowNo, 0, 3077, DisplayType.Search, m_model.getTransfCtaBancariaSqlValidation());
		MLookup lookupTransf = new MLookup(infoTransf, 0);
		transfCtaBancaria = new WSearchEditor( "C_BankAccount_ID",false,false,true,lookupTransf );
	    
        txtTransfNroTransf = new Textbox();
        txtTransfImporte = new Textbox();
        transFecha = new WDateEditor(); // VComponentsFactory.VDateFactory();
//        jPanel7 = new javax.swing.JPanel();
        lblChequeChequera = new Label();
        lblChequeNroCheque = new Label();
        lblChequeImporte = new Label();
        lblChequeFechaEmision = new Label();
        lblChequeFechaPago = new Label();
        lblChequeALaOrden = new Label();
        lblChequeBanco = new Label();
        lblChequeCUITLibrador = new Label(); 
        lblChequeDescripcion = new Label();
        chequeChequera = createChequeChequeraLookup(); 
        txtChequeImporte = new Textbox();
        chequeFechaEmision = new WDateEditor(); // VComponentsFactory.VDateFactory();
        chequeFechaPago = new WDateEditor(); // VComponentsFactory.VDateFactory();
        txtChequeALaOrden = new Textbox();
        txtChequeNroCheque = new Textbox();
        txtChequeBanco = new Textbox();
        cboChequeBancoID = createChequeBancoIDLookup();
        txtChequeCUITLibrador = new Textbox();
        txtChequeDescripcion = new Textbox();     
        
        MLookup lookupCampaign = MLookupFactory.get (Env.getCtx(), m_WindowNo, 0, 2570, DisplayType.TableDir);
        cboCampaign = new WTableDirEditor("C_Campaign_ID", false, false, true, lookupCampaign);
        
        MLookup lookupProject = MLookupFactory.get (Env.getCtx(), m_WindowNo, 0, 1349, DisplayType.TableDir);
        cboProject = new WTableDirEditor("C_Project_ID", false, false, true, lookupProject);
        
        MLookupInfo infoCurrency = VComponentsFactory.MLookupInfoFactory(Env.getCtx(),m_WindowNo, 0, 457, DisplayType.TableDir, m_model.getCurrencySqlValidation());
        MLookup lookupCurrency = new MLookup(infoCurrency, 0);
        cboCurrency = new WTableDirEditor("C_Currency_ID", false, false, true, lookupCurrency);
            
        lblCampaign = new Label();
        lblProject = new Label();
        lblCurrency = new Label();

        cmdProcess = new Button();
        
        cmdCancel = new Button();
        /*
        jPanel11 = new javax.swing.JPanel();
        */
        lblCreditInvoice = new Label();
        MLookupInfo infoCreditInvoice = VComponentsFactory.MLookupInfoFactory( Env.getCtx(),m_WindowNo, 0, 3484, DisplayType.Search, m_model.getCreditSqlValidation());
        MLookup lookupCreditInvoice = new MLookup(infoCreditInvoice, 0);
		creditInvoice = new WSearchEditor("C_Invoice_ID", false, false, true, lookupCreditInvoice);
        
        lblCreditAvailable = new Label();
        txtCreditAvailable = new Textbox();
        txtCreditAvailable.setReadonly(true); // setEditable(false);
        lblCreditImporte = new Label();
        txtCreditImporte = new Textbox();
        
        checkPayAll = new Checkbox();
        checkPayAll.setText("Pagar Todo");
        checkPayAll.addActionListener(new EventListener() {
			
			@Override
			public void onEvent(Event arg0) throws Exception {
				updatePayAllInvoices(false);
				
			}
		});
/*       
        checkPayAll.addAction("setSelected",
				KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),
				new AbstractAction() {
					@Override
					public void actionPerformed(ActionEvent arg0) {
						checkPayAll.setSelected(!((VCheckBox) arg0.getSource()).isSelected());
						fireActionPerformed(checkPayAll.getActionListeners(), null);
					}
				});
*/        
        lblBPartner.setText("Entidad Comercial");

        chequeFechaEmision.setMandatory(true);
        chequeFechaPago.setMandatory(true);
        buttonGroup1.appendChild(radPayTypeStd);
        radPayTypeStd.addEventListener("onCheck", new EventListener() {
			public void onEvent(Event arg0) throws Exception {
				onTipoPagoChange(false);
			}
		});        
        buttonGroup1.appendChild(radPayTypeAdv);
        radPayTypeAdv.setValue("PAGO ADELANTADO");
        radPayTypeAdv.addEventListener("onCheck", new EventListener() {
            public void onEvent(Event arg0) throws Exception {
                onTipoPagoChange(false);
            }
        });

        txtTotalPagar1.setValue("TOTAL A PAGAR");
        lblTotalPagar1.setValue("TOTAL A PAGAR");

        buttonGroup2.appendChild(rInvoiceAll);      
        rInvoiceAll.setSelected(true);
        rInvoiceAll.setValue("TODAS");
        rInvoiceAll.addEventListener("onCheck", new EventListener() {
            public void onEvent(Event arg0) throws Exception {
                onFechaChange(false);
            }
        });

        
        buttonGroup2.appendChild(rInvoiceDate);
        rInvoiceDate.setValue("VENCIDAS A FECHA:");
        rInvoiceDate.addEventListener("onCheck", new EventListener() {
            public void onEvent(Event arg0) throws Exception {
                onFechaChange(false);
            }
        });

        cmdEliminar.setLabel("ELIMINAR");
        cmdEliminar.addEventListener("onClick", new EventListener() {
            public void onEvent(Event evt) throws Exception {
            	cmdEditarActionPerformed(evt);
            }
        });

        cmdEditar.setLabel("EDITAR");
        cmdEditar.addEventListener("onClick", new EventListener() {
            public void onEvent(Event evt) throws Exception {
            	cmdEditarActionPerformed(evt);
            }
        });

          txtSaldo = new Textbox();
          txtSaldo.setReadonly(true); // setEditable(false);
        txtDifCambio = new Textbox();
        txtDifCambio.setReadonly(true); // (false);
        lblSaldo = new Label();
        lblSaldo.setText("SALDO");
        txtMedioPago2 = new Textbox();
        txtMedioPago2.setReadonly(true);
        txtRetenciones2 = new Textbox();
        txtRetenciones2.setReadonly(true);
        txtTotalPagar2 = new Textbox();
        txtTotalPagar2.setReadonly(true);
        lblTotalPagar2 = new Label();
        lblTotalPagar2.setText("TOTAL A PAGAR");
        lblRetenciones2 = new Label();
        lblRetenciones2.setText("RETENCIONES");
        lblDifCambio = new Label();
        lblDifCambio.setText("Diferecia de Cambio");
        lblMedioPago2 = new Label();
        lblMedioPago2.setText("MEDIO DE PAGO");

        cmdGrabar.setLabel("GRABAR");
        cmdGrabar.addEventListener("onClick", new EventListener() {
            public void onEvent(Event evt) throws Exception {
            	cmdSavePMActionPerformed(evt);
            }
        });

        cmdProcess.setLabel("SIGUIENTE/PROCESAR");
        cmdProcess.addActionListener(new EventListener() {
			
			@Override
			public void onEvent(Event arg0) throws Exception {
				 cmdProcessActionPerformed(arg0);
			}
		});

        cmdCancel.setLabel("CANCELAR");
        cmdCancel.addEventListener("onClick", new EventListener() {
            public void onEvent(Event evt) throws Exception {
            	cmdCancelActionPerformed(evt);
            }
        });
        
//        // Pagos anticipados como medios de pago
        createPagoAdelantadoTab();  // FEDE:TODO llamado al menos para que instancie los objetos
//		jTabbedPane2.addTab("PAGO ADELANTADO", createPagoAdelantadoTab());
//		m_PagoAdelantadoTabIndex = jTabbedPane1.indexOfComponent(panelPagoAdelantado);
//        
//        //Agrego un listener para verificar si es null o no, y deshabilitar el boton Siguiente en caso de que sea null
//        
        BPartnerSel.addValueChangeListener(new ValueChangeListener() {
			
			@Override
			public void valueChange(ValueChangeEvent evt) {
				cmdBPartnerSelActionPerformed(evt);
			}
		}); 
//        
//        keyBindingsInit();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Crea la pestaña de efectivo 
     */
    protected Tabpanel createCashTab(){
       
    	txtEfectivoImporte.setText("0");
    	
    	Tabpanel tabpanel = new Tabpanel();
    	tabpanel.setHeight("150px");
    	
    	Grid gridpanel = GridFactory.newGridLayout();
		gridpanel.setWidth("100%");
		
    	Rows rows = gridpanel.newRows();
		Row row = rows.newRow();
		row.appendChild(lblEfectivoLibroCaja.rightAlign());
		row.appendChild(efectivoLibroCaja.getComponent());
		row.appendChild(lblEfectivoImporte.rightAlign());
		row.appendChild(txtEfectivoImporte);
		
		tabpanel.appendChild(gridpanel);
        return tabpanel;
    }
	
    
    /**
     * Crea el panel de pagos
     */
    protected void createPaymentTab(){
    	
    	Div contenedor = new Div();
		
		Tablelayout tablelayout = new Tablelayout();
		tablelayout.setWidth("100%");
		tablelayout.setColumns(2);
		//tablelayout.setStyle("border: 1px solid red");
		
		
		// Panel de la tabla donde se encuentran Campaña, Proyacto y Moneda
		Tablechildren tableCampProy = new Tablechildren(); 
		tableCampProy.setWidth("50%");
		tableCampProy.appendChild(agregarCampProy());
		
		// Panel de la tabla donde se encuentra el Árbol
		Tablechildren tableTree = new Tablechildren();
		tableTree.setWidth("50%");
		tableTree.setHeight("200px");
		tableTree.setRowspan(2);
		tableTree.appendChild(agregarTree());
		
		// Panel de la tabla donde se encuentran los Tabs
		Tablechildren tableTabs = new Tablechildren(); 
		tableTabs.appendChild(agregarTabs());
		
		/****/
		 
		Panel panel4 = new Panel();
		Panelchildren panelchildren4 = new Panelchildren();
		
		Tablechildren table4 = new Tablechildren(); 
		//panelchildren4.setStyle("border: 1px solid red");
		panelchildren4.appendChild(cmdGrabar);
		panel4.appendChild(panelchildren4);
		
		table4.appendChild(panel4);
		/*
		Panel panel5 = new Panel();
		Panelchildren panelchildren5 = new Panelchildren();
		
		Tablechildren table5 = new Tablechildren(); 
		//panelchildren4.setStyle("border: 1px solid red");
		panelchildren5.appendChild(cmdEliminar);
		panelchildren5.appendChild(cmdEditar);
		panel5.appendChild(panelchildren5);
		
		table5.appendChild(panel5);
		*/ 
		/****/
		
		tablelayout.appendChild(tableCampProy);
		tablelayout.appendChild(tableTree);
		tablelayout.appendChild(tableTabs);
		tablelayout.appendChild(table4);
		//tablelayout.appendChild(table5);
		
		contenedor.appendChild(tablelayout);
		jTabbedPane2.appendChild(contenedor);
    }

   
	// Uso de un pago adelantado como parte de una orden de pago
	protected Panel createPagoAdelantadoTab()
	{
		Panel panelPagoAdelantado = new Panel();
		Panelchildren panelChildren = new Panelchildren();
		
		lblPagoAdelantado = new Label();
		lblPagoAdelantado.setText(getModel().isSOTrx()?"COBRO":"PAGO");
        lblPagoAdelantadoImporte = new Label();
        lblPagoAdelantadoImporte.setText("IMPORTE");
        txtPagoAdelantadoImporte = new Textbox();
        txtPagoAdelantadoImporte.setText("0");
//        initFormattedTextField((JFormattedTextField)txtPagoAdelantadoImporte);      
		MLookupInfo info = VComponentsFactory.MLookupInfoFactory( Env.getCtx(),m_WindowNo, 0, 5043, DisplayType.Search, getModel().getPagoAdelantadoSqlValidation());
		Lookup lookup = new MLookup(info, 0);
		pagoAdelantado = new WSearchEditor("C_Payment_ID", false, false, true, lookup);
        
        info = VComponentsFactory.MLookupInfoFactory( Env.getCtx(),m_WindowNo, 0, 5283, DisplayType.Search, getModel().getCashAnticipadoSqlValidation());
		lookup = new MLookup(info, 0);
		cashAdelantado = new WSearchEditor("C_Payment_ID", false, false, true, lookup);
     
        lblPagoAdelantadoType = new Label();
        lblPagoAdelantadoType.setText("TIPO");
        cboPagoAdelantadoType = new Combobox();
        cboPagoAdelantadoType.appendItem(getMsg("Payment"));
        cboPagoAdelantadoType.appendItem(getMsg("Cash"));		
        // Por defecto pago
        cboPagoAdelantadoType.setSelectedIndex(PAGO_ADELANTADO_TYPE_PAYMENT_INDEX); 
        cboPagoAdelantadoType.addEventListener("onChange", new EventListener() {
        	public void onEvent(Event arg0) throws Exception {
				updatePagoAdelantadoTab();
			}
		});
        txtPagoAdelantadoAvailable = new Textbox();
        txtPagoAdelantadoAvailable.setReadonly(true); 
        lblPagoAdelantadoAvailable = new Label();
        lblPagoAdelantadoAvailable.setText("PENDIENTE");
		
        Grid gridpanel = GridFactory.newGridLayout();
		gridpanel.setWidth("100%");
		        
        updatePagoAdelantadoTab();

        panelPagoAdelantado.appendChild(panelChildren);
        
        // FEDE:TODO falta completar
        
		return panelPagoAdelantado;	
	}    
    
    private void cmdSavePMActionPerformed(Event evt) {//GEN-FIRST:event_cmdSavePMActionPerformed

    	try {
    		
	    	VOrdenPagoModel.MedioPago mp = null;
	    	
	    	switch (jTabbedPane2.getIndex())
	    	{
	    	case 0: // Efectivo
	    		mp = saveCashMedioPago();
	    		break;
	    		
	    	case 1: // Transferencia
	    		mp = saveTransferMedioPago();
	    		break;
	    		
	    	case 2: // Cheque
	    		mp = saveCheckMedioPago();
				break;
	    	case 3: // Crédito
	    		mp = saveCreditMedioPago();
	    		break;
	    	case 4:
				// Adelantado
	    		mp = savePagoAdelantadoMedioPago();
	    		break;
	    	default:
	    		cmdCustomSaveMedioPago(jTabbedPane2.getIndex());
	    		break;
	    	}
	    	
	    	if(mp != null){
	    		m_model.addMedioPago(mp);
	    	}
	    	clearMediosPago();
			// Actualizar componentes de interfaz gráfica necesarios luego de
			// agregar el medio de pago 
	    	updateCustomInfoAfterMedioPago(MEDIOPAGO_ACTION_INSERT);
    	} catch (Exception e) {
    		String title = Msg.getMsg(m_ctx, "Error");
    		String msg = Msg.parseTranslation(m_ctx, "@SaveErrorNotUnique@ \n\n" + e.getMessage() /*"@SaveError@"*/ );
    		
    		// TODO: VER
    		//JOptionPane.showMessageDialog(this, msg, title, JOptionPane.ERROR_MESSAGE);
    		
    	}
    }//GEN-LAST:event_cmdSavePMActionPerformed
    
    
    protected MedioPagoEfectivo saveCashMedioPago() throws Exception{
    	MedioPagoEfectivo mpe = m_model.getNuevoMedioPagoEfectivo();
    	try {
			mpe.monedaOriginalID = (Integer) cboCurrency.getValue();
		} catch (Exception e) {
			throw new Exception(cboCurrency.getValue().toString());
		}
		try {
			mpe.importe = numberParse(txtEfectivoImporte.getText());
		} catch (Exception e) {
			throw new Exception(lblEfectivoImporte.getValue());
		}		
		try {
			mpe.libroCaja_ID = (Integer)efectivoLibroCaja.getValue();
		} catch (NullPointerException ee) {
			throw new Exception(lblEfectivoLibroCaja.getValue());
		}
		if (mpe.importe.compareTo(new BigDecimal(0.0)) <= 0)
			throw new Exception(lblEfectivoImporte.getValue());

		mpe.setCampaign(getC_Campaign_ID() == null?0:getC_Campaign_ID());
		mpe.setProject(getC_Project_ID() == null?0:getC_Project_ID());
		
		return mpe;
    }
    
    
    protected MedioPagoTransferencia saveTransferMedioPago() throws Exception{
    	MedioPagoTransferencia mpt = m_model.getNuevoMedioPagoTransferencia();		
    	try {
			mpt.monedaOriginalID = (Integer) cboCurrency.getValue();
		} catch (Exception e) {
			throw new Exception(cboCurrency.getValue().toString());
		}
		try {
			mpt.C_BankAccount_ID = (Integer)transfCtaBancaria.getValue();
		} catch (NullPointerException ee) {
			throw new Exception(lblTransfCtaBancaria.getValue());
		}		
		mpt.fechaTransf = Timestamp.valueOf(transFecha.getValue().toString());		
		try {
			mpt.importe = numberParse(txtTransfImporte.getText());
		} catch (Exception e) {
			throw new Exception(lblTransfImporte.getValue());
		}		
		mpt.nroTransf = txtTransfNroTransf.getText();
		
		if (mpt.fechaTransf == null)
			throw new Exception(lblTransfFecha.getValue());
		
		if (mpt.importe.compareTo(new BigDecimal(0.0)) <= 0)
			throw new Exception(lblTransfImporte.getValue());
		
		if (mpt.nroTransf.trim().equals(""))
			throw new Exception(lblTransfNroTransf.getValue());
		
		mpt.setCampaign(getC_Campaign_ID() == null?0:getC_Campaign_ID());
		mpt.setProject(getC_Project_ID() == null?0:getC_Project_ID());
		
		return mpt;
    }
    
    
    protected MedioPagoCheque saveCheckMedioPago() throws Exception{
    	MedioPagoCheque mpc = m_model.getNuevoMedioPagoCheque();		
		mpc.aLaOrden = txtChequeALaOrden.getText();		
		try {
			mpc.monedaOriginalID = (Integer) cboCurrency.getValue();
		} catch (Exception e) {
			throw new Exception(cboCurrency.getValue().toString());
		}
		try {
			mpc.chequera_ID = (Integer)chequeChequera.getValue();
		} catch (Exception e) {
			throw new Exception(lblChequeChequera.getValue());
		}		
		mpc.fechaEm = Timestamp.valueOf(chequeFechaEmision.getValue().toString());
		mpc.fechaPago = Timestamp.valueOf(chequeFechaPago.getValue().toString());
		try {	    		
			mpc.importe = numberParse(txtChequeImporte.getText());
		} catch (Exception e) {
			throw new Exception(lblChequeImporte.getValue());
		}		
		mpc.nroCheque = txtChequeNroCheque.getText(); 
		mpc.banco = txtChequeBanco.getText().trim();
		mpc.cuitLibrador = txtChequeCUITLibrador.getText().trim();
		mpc.descripcion = txtChequeDescripcion.getText().trim();
		
		// A La Orden: Campo no obligatorio
		//
		// if (mpc.aLaOrden.trim().equals(""))
		// 	throw new Exception("");
		
		if (mpc.fechaEm == null)
			throw new Exception(lblChequeFechaEmision.getValue());
		
		if (mpc.fechaPago == null)
			throw new Exception(lblChequeFechaPago.getValue());
		
		if (mpc.fechaPago.compareTo(mpc.fechaEm) < 0) {
			throw new Exception(getMsg("InvalidCheckDueDate"));
		}
		
		if (mpc.importe.compareTo(new BigDecimal(0.0)) <= 0)
			throw new Exception(lblChequeImporte.getValue());
		
		if (mpc.nroCheque.trim().equals(""))
			throw new Exception(lblChequeNroCheque.getValue());
		
		mpc.setCampaign(getC_Campaign_ID() == null?0:getC_Campaign_ID());
		mpc.setProject(getC_Project_ID() == null?0:getC_Project_ID());
		
		// Se actualiza la secuencia de nros de cheque de la chequera en caso de ser posible.
		if (isActualizarNrosChequera()) {
			String nroChequeStr = mpc.nroCheque.trim();
			try {
				int nroCheque = Integer.parseInt(nroChequeStr);
				// El numero de cheque es numérico.
				int C_BankAccountDoc_ID = mpc.chequera_ID;
				// Se incrementa en 1 el numero de cheque;
				nroCheque++;
				// Se guarda el siguiente numero de cheque en la chequera.
				X_C_BankAccountDoc bankAccountDoc = new X_C_BankAccountDoc(Env.getCtx(),C_BankAccountDoc_ID,null);
				bankAccountDoc.setCurrentNext(nroCheque);
				bankAccountDoc.save();
				bankAccountDoc = null;
			} catch (Exception e) {
				// El usuario modifico el numero de cheque agregandole caracteres que no son numericos.
				// En este caso no se actualiza la secuencia de la chequera.
			}
		}
		
		return mpc;
    }
    
    
    protected MedioPagoCredito saveCreditMedioPago() throws Exception{
    	MedioPagoCredito mpcm = m_model.getNuevoMedioPagoCredito();
    	try {
			mpcm.monedaOriginalID = (Integer) cboCurrency.getValue();
		} catch (Exception e) {
			throw new Exception(cboCurrency.getValue().toString());
		}
		try {
			mpcm.setC_invoice_ID((Integer)creditInvoice.getValue());
		} catch (Exception ee) {
			throw new Exception(lblCreditInvoice.getValue());
		}
		
		try {
			mpcm.setAvailableAmt(getModel().getCreditAvailableAmt(mpcm.getC_invoice_ID() ) );
		} catch (Exception e) {
			throw new Exception(lblCreditAvailable.getValue());
		}
		
		try {
			mpcm.setImporte(numberParse(txtCreditImporte.getText()));
		} catch (Exception e) {
			throw new Exception(lblCreditImporte.getValue());
		}
		
		mpcm.validate();

		mpcm.setCampaign(getC_Campaign_ID() == null?0:getC_Campaign_ID());
		mpcm.setProject(getC_Project_ID() == null?0:getC_Project_ID());
		return mpcm;
    }
    
	protected MedioPago savePagoAdelantadoMedioPago() throws Exception {
		// Obtengo los datos de la interfaz
		boolean isCash = cboPagoAdelantadoType.getSelectedIndex() == PAGO_ADELANTADO_TYPE_CASH_INDEX;
		Integer payID = null;
		BigDecimal amount = null;
		Integer monedaOriginalID;
		
		payID = (Integer)(isCash ? cashAdelantado.getValue() : pagoAdelantado.getValue());
		
		try {
			monedaOriginalID = (Integer) cboCurrency.getValue();
		} catch (Exception e) {
			throw new Exception(cboCurrency.getValue().toString());
		}
		try {
			amount = numberParse(txtPagoAdelantadoImporte.getText());
		} catch (Exception e) {
			throw new Exception("@Invalid@ @Amount@");
		}
		// Se agrega el cobro adelantado como medio de cobro
		return getModel().addPagoAdelantado(payID, amount, isCash, monedaOriginalID);		
	}
    
/*    
    private VOrdenPagoModel.MyTreeNode darElementoArbolSeleccionado() {
    	if (jTree1.getSelectionCount() == 1) {
			TreePath path = jTree1.getSelectionPath();
			
			VOrdenPagoModel.MyTreeNode tn = (VOrdenPagoModel.MyTreeNode)path.getLastPathComponent();
			return tn;
    	}
    	
    	return null;
    }
*/    
    private void cmdEditarActionPerformed(Event evt) {//GEN-FIRST:event_cmdEditarActionPerformed
//    	try {
//			VOrdenPagoModel.MyTreeNode tn = darElementoArbolSeleccionado();
//			if (tn != null) {
//				cmdEditMedioPago(tn);
//				// Actualizar componentes de interfaz gráfica necesarios luego de
//				// agregar el medio de pago 
//		    	updateCustomInfoAfterMedioPago(MEDIOPAGO_ACTION_EDIT);
//			}
//    	} catch (Exception e) {
//    		
//    	}
    }//GEN-LAST:event_cmdEditarActionPerformed

    private void cmdEliminarActionPerformed(Event evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
//    	try {
//			VOrdenPagoModel.MyTreeNode tn = darElementoArbolSeleccionado();
//
//			if (tn != null) {
//				cmdDeleteMedioPago(tn);
//				// Actualizar componentes de interfaz gráfica necesarios luego de
//				// agregar el medio de pago 
//		    	updateCustomInfoAfterMedioPago(MEDIOPAGO_ACTION_DELETE);
//			}
//    	} catch (Exception e) {
//    		
//    	}
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void onFechaChange(boolean toPayMoment) {//GEN-FIRST:event_onFechaChange
    	if (rInvoiceAll.isSelected()) {
    		invoiceDatePick.setValue(new Date());
    		invoiceDatePick.setReadonly(true); // setReadWrite(false);
    	} else {
    		invoiceDatePick.setReadonly(false); // ReadWrite(true);
    	}
    	
    	m_model.setFechaTablaFacturas(new Timestamp(((Date)invoiceDatePick.getValue()).getTime()), rInvoiceAll.isSelected());
    	updatePayAllInvoices(toPayMoment);
    }//GEN-LAST:event_onFechaChange

    private void onTipoPagoChange(boolean toPayMoment) {//GEN-FIRST:event_onTipoPagoChange
    	if (radPayTypeStd.isSelected()) {
    		tblFacturas.setAttribute("ReadOnly", "false"); // setEnabled(true);
    		txtTotalPagar1.setReadonly(true);
    		rInvoiceAll.setDisabled(false);
    		rInvoiceDate.setDisabled(false);
    	} else {
    		tblFacturas.setAttribute("ReadOnly", "true"); // setEnabled(false);
    		txtTotalPagar1.setReadonly(false);
    		rInvoiceAll.setSelected(true);
    		rInvoiceAll.setDisabled(false);
    		rInvoiceDate.setDisabled(true);
    		//forzo la verificación de la entidad comercial
    		this.cmdBPartnerSelActionPerformed(null);
    		
    		//
    		
    	}

    	m_model.setPagoNormal(radPayTypeStd.isSelected(), null);
    	
    	onFechaChange(toPayMoment);
    	// Actualizar custom de las subclases
    	updateCustomTipoPagoChange();
    }//GEN-LAST:event_onTipoPagoChange

    
    protected void updatePayAllInvoices(boolean toPayMoment){
    	getModel().updatePayAllInvoices(checkPayAll.isSelected(), toPayMoment);
		// tblFacturas.renderAll(); // repaint();
		resetModel();
    }

    private void cmdCancelActionPerformed(Event evt) {//GEN-FIRST:event_cmdCancelActionPerformed
    	dispose();   	
    }//GEN-LAST:event_cmdCancelActionPerformed
    
    protected void showError(String msg) {
		//String title = Msg.getMsg(m_ctx, "Error");
		String translatedMsg = Msg.parseTranslation(m_ctx, msg /*"@SaveError@"*/ );
		
		FDialog.error(m_WindowNo, this, translatedMsg);
		
    }
	
	/**
	 * Mostrar una ventana dialog con el mensaje parámetro
	 * 
	 * @param msg
	 *            clave ad_message de un mensaje o la descripción de un mensaje.
	 */
    protected void showInfo(String msg){
    	// TODO: VER
    	FDialog.info(m_WindowNo, this, msg);
    }
    
    private void cmdProcessActionPerformed(Event evt) {

    	final int idx = jTabbedPane1.getIndex();
    	
    	if (idx == 0) {

    		clearMediosPago();
    		// Procesar
    		
    		BigDecimal monto = null;
    		
    		try {
    			monto = numberParse(txtTotalPagar1.getText());
    		} catch (ParseException e) {
    			showError("@SaveErrorNotUnique@ \n\n" + lblTotalPagar1.getValue());
    			
        		txtTotalPagar1.setFocus(true); // .requestFocusInWindow();
        		txtTotalPagar1.getValue().substring(0, txtTotalPagar1.getText().length() - 1); // .select(0, txtTotalPagar1.getText().length() - 1);
        		
        		return;
    		}
    		
    		m_model.setActualizarFacturasAuto(false);
    		// Fuerzo la actualizacion de los valores de la interfaz
    		onTipoPagoChange(true);
    		m_model.setPagoNormal(radPayTypeStd.isSelected(), monto);
    		m_model.setActualizarFacturasAuto(true);
    		m_model.setDocumentNo(fldDocumentNo.getText());
    		// Realizar acciones antes del PreProcesar
    		try {
        		makeOperationsBeforePreProcesar();
			} catch (Exception e) {
				showError("Se produjo un error al pre procesar. "+e.getMessage());
				return;
			}
  		
    		int status = m_model.doPreProcesar();
    		
    		switch ( status )
    		{
    		case VOrdenPagoModel.PROCERROR_OK:
    			break;
    			
    		case VOrdenPagoModel.PROCERROR_INSUFFICIENT_INVOICES:
    			showError("@InsufficientInvoicesToPayError@");
    			return;
    		
    		case VOrdenPagoModel.PROCERROR_NOT_SELECTED_BPARTNER:
    			showError("@NotSelectedBPartner@");
    			return;

    		case VOrdenPagoModel.PROCERROR_DOCUMENTNO_NOT_SET:
    			showError("Debe indicar el número de documento");
    			return;
    		
    		case VOrdenPagoModel.PROCERROR_DOCUMENTNO_ALREADY_EXISTS:
    			showError("Número de documento ya existente");
    			return;
    		
    		case VOrdenPagoModel.PROCERROR_DOCUMENTTYPE_NOT_SET:
    			showError("Debe indicar el tipo de documento");
    			return;
    			
    		case VOrdenPagoModel.PROCERROR_BOTH_EXCHANGE_INVOICES:
    			showError("@BothExchangeInvoices@");
    			return;
    			
    		default:
    			showError("@ValidationError@");
    			return;
    		}
    		
			// Actualizo componentes gráficos antes de pasar a la siguiente
			// pestaña
    		updateComponentsPreProcesar();
    		// Avanza a la siguiente tab
    		m_cambioTab = true;
    		tabbox.setSelectedIndex(1);
    		m_cambioTab = false;
    		
    		updatePaymentsTabsState();
//    		treeUpdated();
    		// Actualizar descuento de entidad comercial
    		customUpdateBPartnerRelatedComponents(false);
    		
    	} else if (idx == 1) {
    		getModel().setDescription(txtDescription.getText());
    		
    		m_model.setProjectID(getC_Project_ID() == null?0:getC_Project_ID());
    		m_model.setCampaignID(getC_Campaign_ID() == null?0:getC_Campaign_ID());
    		BigDecimal exchangeDifference = getModel().calculateExchangeDifference();
    		m_model.setExchangeDifference( exchangeDifference == null?BigDecimal.ZERO:exchangeDifference);
    		
    		int status = m_model.doPostProcesar();
    		
    		switch (status) 
    		{
    		case VOrdenPagoModel.PROCERROR_OK:
    			break;
    		
    		case VOrdenPagoModel.PROCERROR_PAYMENTS_AMT_MATCH:
    			showError("@PaymentsAmtMatchError@");
    			break;
    			
    		case VOrdenPagoModel.PROCERROR_PAYMENTS_GENERATION:
    			showError("@PaymentsGenerationError@ : "+ this.m_model.getMsgAMostrar());
    			break;
    			
    		default:
    			showError("@Error@"+ this.m_model.getMsgAMostrar());
    			break;
    		}
    		
    		if (status == VOrdenPagoModel.PROCERROR_OK)
    		{
// FEDE:TODO: Mostrar informe bajo contexto Web!
//	    		m_model.mostrarInforme(this);
	    		
	    		// Reset	    		
	    		reset();
    		}
    		//else
    			//m_model.initTrx();

    	}    	
    }//GEN-LAST:event_cmdProcessActionPerformed
    
    /**
     * Metodo que determina el valor que se encuentra dentro de la entidad comercial.
     * Si es null y está seteado el radio button de pago anticipado, no se puede pasar a Siguiente.
     * Para que el boton Siguiente se encuentre habilitado, debería ingresar una entidad comercial en el LookUP
     * @param evt
     */
    private void cmdBPartnerSelActionPerformed(ValueChangeEvent evt){
    	if((this.BPartnerSel.getValue() == null)){
    		this.cmdProcess.setEnabled(false);
    	}
    	else{
    		this.cmdProcess.setEnabled(true);
    	}
    }
    
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    
    protected WSearchEditor BPartnerSel;
    protected Textbox fldDocumentNo;
    
    private Radiogroup buttonGroup1;
    private Radiogroup buttonGroup2;
   
    protected WTableDirEditor cboCampaign;
    protected WTableDirEditor cboClient;
    protected WTableDirEditor cboOrg;
    protected WTableDirEditor cboProject;
    protected WTableDirEditor cboCurrency;
    
    protected WTableDirEditor chequeChequera;
    protected WDateEditor chequeFechaEmision;
    protected WDateEditor chequeFechaPago;
    protected Button cmdCancel;
    
    protected Button cmdEditar;
    protected Button cmdEliminar;
    protected Button cmdGrabar;
    protected Button cmdProcess;
 
    protected WSearchEditor efectivoLibroCaja;    
    
    protected Datebox invoiceDatePick;
    protected Grid jPanel1;
    
    // Tabs
    private Tabpanel jTabbedPane1 = new Tabpanel();
    private Tabpanel jTabbedPane2 = new Tabpanel();
 	private Tabbox tabbox = new Tabbox();
 	private Tabs tabs = new Tabs();
 	private Tabpanels tabpanels = new Tabpanels();
    
    protected Label lblBPartner;
    protected Label lblCampaign;
    protected Label lblChequeALaOrden;
    protected Label lblChequeChequera;
    protected Label lblChequeFechaEmision;
    protected Label lblChequeFechaPago;
    protected Label lblChequeImporte;
    protected Label lblChequeNroCheque;
    protected Label lblChequeDescripcion;
    protected Label lblClient;
    protected Label lblDocumentNo;
    private Label lblDescription;
    protected Label lblDocumentType;
    protected WTableDirEditor cboDocumentType;
    
    protected Label lblEfectivoImporte;
    protected Label lblEfectivoLibroCaja;
    protected Label lblMedioPago2;
    protected Label lblOrg;
    protected Label lblProject;
    protected Label lblCurrency;
    
    protected Label lblRetenciones2;
    protected Label lblDifCambio;
    protected Label lblSaldo;
    protected Label lblTotalPagar1;
    
    protected Label lblTotalPagar2;
    protected Label lblTransfCtaBancaria;
    protected Label lblTransfFecha;
    protected Label lblTransfImporte;
    protected Label lblTransfNroTransf;
    /*
    protected javax.swing.JPanel panelCamProy;
    */
    protected Radio rInvoiceAll;
    protected Radio rInvoiceDate;
    protected Radio radPayTypeAdv;
    protected Radio radPayTypeStd;
    protected Checkbox checkPayAll;
    
    protected FacturasModel listModel;
    protected Grid tblFacturas;
    protected GridRenderer renderer;
    protected WDateEditor transFecha;
    protected WSearchEditor transfCtaBancaria;

    protected Textbox txtDescription;
    
    protected Textbox txtChequeALaOrden;
    protected Textbox txtChequeImporte;
    protected Textbox txtChequeNroCheque;
    protected Textbox txtChequeDescripcion;
    
    protected Textbox txtEfectivoImporte;
    
    protected Textbox txtMedioPago2;
    protected Textbox txtRetenciones2;
    protected Textbox txtSaldo;
    protected Textbox txtDifCambio;
    
    protected Textbox txtTotalPagar1;
    
    protected Textbox txtTotalPagar2;
    protected Textbox txtTransfImporte;
    protected Textbox txtTransfNroTransf;
    // Fin de declaraci�n de variables//GEN-END:variables

    protected Label lblCreditInvoice;
    protected WSearchEditor creditInvoice;
    protected Label lblCreditImporte;
    protected Textbox txtCreditImporte;
    protected Label lblCreditAvailable;
    protected Textbox txtCreditAvailable;
	protected Label lblChequeBanco;
	protected Label lblChequeCUITLibrador;
	protected Textbox txtChequeBanco;
	protected WSearchEditor cboChequeBancoID;
	protected Textbox txtChequeCUITLibrador;
    protected Label lblPagoAdelantado;
    
    protected Label lblPagoAdelantadoImporte;
    protected Textbox txtPagoAdelantadoImporte;
    
    protected WSearchEditor pagoAdelantado;
    protected WSearchEditor cashAdelantado;
    protected Combobox cboPagoAdelantadoType;
    protected Label lblPagoAdelantadoType;
    protected Label lblPagoAdelantadoAvailable;
    protected Textbox txtPagoAdelantadoAvailable;

    protected static final int PAGO_ADELANTADO_TYPE_PAYMENT_INDEX = 0;
    protected static final int PAGO_ADELANTADO_TYPE_CASH_INDEX = 1;
//        
    protected MSequence seq;
    
    private int m_PagoAdelantadoTabIndex = -1;
    private int m_chequeTerceroTabIndex = -1;
    
    private Panel panelChequeTercero;
    private Label lblChequeTerceroCuenta;
    private Label lblChequeTercero;
    private Label lblChequeTerceroImporte;
    private Label lblChequeTerceroDescripcion;
    private WSearchEditor chequeTerceroCuenta;
    private WSearchEditor chequeTercero;
    private Textbox txtChequeTerceroImporte;
    private Textbox txtChequeTerceroDescripcion;
//    
//    // Variables //

      private boolean m_cambioTab = false;
//    
      protected int m_C_Currency_ID = Env.getContextAsInt( Env.getCtx(), "$C_Currency_ID" );
//
      private static CLogger log = CLogger.getCLogger( WOrdenPago.class );
      protected VOrdenPagoModel m_model = new VOrdenPagoModel();
      protected Properties m_ctx = Env.getCtx();
      private String m_trxName = m_model.getTrxName();
    
      private boolean actualizarNrosChequera = true;

    protected static final String GOTO_BPARTNER = "GOTO_BPARTNER";
    protected static final String MOVE_INVOICE_FORWARD = "MOVE_INVOICE_FORWARD";
    protected static final String MOVE_INVOICE_BACKWARD = "MOVE_INVOICE_BACKWARD";
    protected static final String GOTO_PROCESS = "GOTO_PROCESS";
    protected static final String GOTO_EXIT = "GOTO_EXIT";
    protected static final String ADD_PAYMENT = "ADD_PAYMENT";
    protected static final String EDIT_PAYMENT = "EDIT_PAYMENT";
    protected static final String REMOVE_PAYMENT = "REMOVE_PAYMENT";
    protected static final String GO_BACK = "GO_BACK";
    protected static final String MOVE_PAYMENT_FORWARD = "MOVE_PAYMENT_FORWARD";
    protected static final String MOVE_PAYMENT_BACKWARD = "MOVE_PAYMENT_BACKWARD";
    protected static final String GOTO_PAYALL = "GOTO_PAYALL";
    
    protected static final Integer TAB_INDEX_EFECTIVO = 0;
    protected static final Integer TAB_INDEX_TRANSFERENCIA = 1;
    protected static final Integer TAB_INDEX_CHEQUE = 2;
    protected static final Integer TAB_INDEX_CREDITO = 3;
    protected static final Integer TAB_INDEX_PAGO_ADELANTADO = 4;
    
    protected static final Integer MEDIOPAGO_ACTION_INSERT = 0;
    protected static final Integer MEDIOPAGO_ACTION_EDIT = 1;
    protected static final Integer MEDIOPAGO_ACTION_DELETE = 2;

    
	protected void customInitComponents() {
		
		Date d = new Date();
		
		invoiceDatePick.setValue(d);
		
		
		clearMediosPago();
		
		//
		
		txtTotalPagar1.setText("");
		
		txtSaldo.setText("");
		txtDifCambio.setText("");
		txtTotalPagar2.setText("");
		txtRetenciones2.setText("");
		txtMedioPago2.setText("");
		txtDescription.setText("");

		txtCreditAvailable.setText("");
		txtPagoAdelantadoAvailable.setText("");
	
		//
		cboCurrency.addValueChangeListener(this);
		efectivoLibroCaja.addValueChangeListener(this);
		transfCtaBancaria.addValueChangeListener(this);
		chequeChequera.addValueChangeListener(this);
		BPartnerSel.addValueChangeListener(this);
		
		chequeFechaEmision.addValueChangeListener(this);
		chequeFechaPago.addValueChangeListener(this);
		invoiceDatePick.addEventListener("onClick", this); // addValueChangeListener(this);
		transFecha.addValueChangeListener(this);
		
		tblFacturas.addEventListener("onChange", this); // addValueChangeListener(this);
		getModel().m_facturasTableModel.addTableModelListener(new TableModelListener() {
			public void tableChanged(TableModelEvent e) {
				// Se verifica que no se esté intentando pagar una factura que no tiene una tasa de cambio para la fecha actual
				validateConversionRate();
				tableUpdated();		
				resetModel();
			}
		});

		// tblFacturas.getDefaultEditor(BigDecimal.class).addCellEditorListener(this);
		// TableCellEditor cellEd = tblFacturas.getDefaultEditor(BigDecimal.class); 
//		TableCellEditor cellEd = new DecimalEditor(BigDecimal.ZERO, new BigDecimal(Integer.MAX_VALUE), m_model.getNumberFormat());
//		int cc = tblFacturas.getColumnModel().getColumnCount();
//		TableColumn tc = tblFacturas.getColumnModel().getColumn(cc - 1);
//		tc.setCellEditor(cellEd);
//		cellEd.addCellEditorListener(this); 
		
		// TableCellRenderer cellRend = tblFacturas.getDefaultRenderer(Float.class);
		// tblFacturas.setDefaultRenderer(Number.class, cellRend);
//		tblFacturas.getColumnModel().getColumn(tblFacturas.getColumnModel().getColumnCount() - 1).setCellRenderer(new MyNumberTableCellRenderer(m_model.getNumberFormat()));
//		tblFacturas.getColumnModel().getColumn(tblFacturas.getColumnModel().getColumnCount() - 2).setCellRenderer(new MyNumberTableCellRenderer(m_model.getNumberFormat()));		

        cboClient.setReadWrite(false);
        cboClient.setValue(Env.getAD_Client_ID(m_ctx));
        cboOrg.setMandatory(true);
        cboOrg.addValueChangeListener(this);
        cboOrg.setValue(Env.getAD_Org_ID(m_ctx));
        
        cboDocumentType.setMandatory(true);
        cboDocumentType.addValueChangeListener(this);

        // campo para numero de documento
//        fldDocumentNo.setMandatory(true);
        
        updateOrg((Integer)cboOrg.getValue());
		
        String Element_MC = Env.getContext(m_ctx,"$Element_MC");
        String Element_PJ = Env.getContext(m_ctx,"$Element_PJ");
        
        cboCampaign.setVisible("Y".equals(Element_MC));
        cboCampaign.setMandatory(false);
        cboCampaign.setValue(null);
//        cboCampaign.refresh();
        
        cboProject.setVisible("Y".equals(Element_PJ));
        cboProject.setMandatory(false);
        cboProject.setValue(null);
//        cboProject.refresh();
        
        cboCurrency.setMandatory(true);
        cboCurrency.setValue(m_C_Currency_ID);
//        cboCurrency.refresh();
        setCurrencyContext();

        // Cuando cambia el documento de crédito, se carga el 
        // importe disponible en el text correspondiente
        creditInvoice.addValueChangeListener(new ValueChangeListener() {
			public void valueChange(ValueChangeEvent evt) {
				Integer invoiceID = (Integer)creditInvoice.getValue();
				if (invoiceID != null)
					txtCreditAvailable.setText(getModel().numberFormat(getModel().getCreditAvailableAmt(invoiceID)));
			}
		});
        
    	BPartnerSel.addValueChangeListener(new ValueChangeListener() {
			public void valueChange(ValueChangeEvent evt) {
				setBPartnerContext();
			}
		});
    	
    	cboCurrency.addValueChangeListener(new ValueChangeListener() {
			public void valueChange(ValueChangeEvent evt) {
				setCurrencyContext();
    			updatePayAmt(getModel().getSaldoMediosPago());
			}
		});
        // Cuando cambia el documento de pago adelantado, se carga el 
        // importe disponible en el text correspondiente
        pagoAdelantado.addValueChangeListener(new ValueChangeListener() {
			public void valueChange(ValueChangeEvent evt) {
				Integer paymentID = (Integer)pagoAdelantado.getValue();
				if (paymentID != null)
					txtPagoAdelantadoAvailable.setText(getModel().numberFormat(getModel().getPagoAdelantadoAvailableAmt(paymentID)));
			}
		});

        // Cuando cambia el documento de efectivo adelantado, se carga el 
        // importe disponible en el text correspondiente
        cashAdelantado.addValueChangeListener(new ValueChangeListener() {
			public void valueChange(ValueChangeEvent evt) {
				Integer cashLineID = (Integer)cashAdelantado.getValue();
				if (cashLineID != null)
					txtPagoAdelantadoAvailable.setText(getModel().numberFormat(getModel().getCashAdelantadoAvailableAmt(cashLineID)));
			}
		});
        
        // Total a pagar 1
    	updateTotalAPagar1();
        // Agregado de pestañas con otras formas de pago. Método vacío que deben
        // implementar las subclases en caso de que quieran agregar otras pestañas.
        addCustomPaymentTabs(jTabbedPane2);
        // Agregado de operaciones luego de crear las pestañas custom
        addCustomOperationAfterTabsDefinition();
        
	}
	
	protected void initTranslations() {
		/*
		String name;
		
		 */
		// Efectivo
		
		lblEfectivoImporte.setText(Msg.translate(Env.getCtx(), "Amount"));
		lblEfectivoLibroCaja.setText(Msg.translate(Env.getCtx(), "C_CashBook_ID"));
		/*
		// Transferencia 
		
		lblTransfCtaBancaria.setText(Msg.getElement(m_ctx, "C_BankAccount_ID"));
		lblTransfFecha.setText(Msg.getMsg(m_ctx, "Date"));
		lblTransfImporte.setText(Msg.getElement(m_ctx, "Amount"));
		lblTransfNroTransf.setText(Msg.getMsg(m_ctx, "TransferNumber"));
		
		// Cheques
		
		lblChequeALaOrden.setText(Msg.getMsg(m_ctx, "ALaOrden"));
		lblChequeChequera.setText(Msg.getElement(m_ctx, "CheckAccount"));
		lblChequeFechaEmision.setText(Msg.getMsg(m_ctx, "EmittingDate"));
		lblChequeFechaPago.setText(Msg.getElement(m_ctx, "PayDate"));
		lblChequeImporte.setText(Msg.getElement(m_ctx, "Amount"));
		lblChequeNroCheque.setText(Msg.getElement(m_ctx, "CheckNo"));
		lblChequeBanco.setText(Msg.translate(m_ctx, "C_Bank_ID"));
		lblChequeCUITLibrador.setText(Msg.translate(m_ctx, "CUITLibrador"));
		lblChequeDescripcion.setText(getMsg("Description"));
		
		// Credito
		lblCreditInvoice.setText(Msg.translate(m_ctx, "Credit"));
		lblCreditAvailable.setText(Msg.translate(m_ctx, "OpenAmt"));
		lblCreditImporte.setText(Msg.getElement(m_ctx, "Amount"));
		
		//
		*/
		// TODO: VER
		//lblBPartner.setText(Msg.getElement(m_ctx, "C_BPartner_ID")+" "+KeyUtils.getKeyStr(getActionKeys().get(GOTO_BPARTNER)));
		lblBPartner.setText(Msg.translate(Env.getCtx(), "C_BPartner_ID"));
		
		lblTotalPagar1.setText(Msg.translate(Env.getCtx(), "Amount"));
		
		lblDescription.setText(Msg.translate(Env.getCtx(), "Description"));
		
		radPayTypeStd.setLabel(Msg.translate(Env.getCtx(), "StandardPayment"));
		radPayTypeAdv.setLabel(Msg.translate(Env.getCtx(), "AdvancedPayment"));
		
		/*
		lblTotalPagar2.setText(Msg.getElement(m_ctx, "Amount"));
		lblMedioPago2.setText(Msg.getElement(m_ctx, "TenderType"));
		lblRetenciones2.setText(Msg.getElement(m_ctx, "C_Withholding_ID"));
		lblDifCambio.setText(Msg.getMsg(m_ctx, "ExchangeDifference"));
		*/
		
		rInvoiceAll.setLabel(Msg.translate(Env.getCtx(), "SearchAND"));
		//rInvoiceDate.setText(Msg.translate(m_ctx, "DueStart"));
		rInvoiceDate.setLabel(Msg.translate(Env.getCtx(), "BeforeDueDate"));
		
		/*
		//TODO: VER
		checkPayAll.setText(Msg.translate(Env.getCtx(), "PayAll"));
		/*
		checkPayAll.setText(Msg.getMsg(m_ctx, "PayAll") + " "
				+ KeyUtils.getKeyStr(getActionKeys().get(GOTO_PAYALL)));
		
		// Saldo Total
		name = VModelHelper.GetReferenceValueTrlFromColumn("I_ReportLine", "AmountType", "BT", "name");
		lblSaldo.setText(name != null ? name : "");
		
		//
		*/
		cmdProcess.setLabel(Msg.translate(Env.getCtx(), "Processing"));
		cmdEditar.setLabel(Msg.translate(Env.getCtx(), "Edit"));
		cmdEliminar.setLabel(Msg.translate(Env.getCtx(), "Delete"));
		cmdGrabar.setLabel(Msg.translate(Env.getCtx(), "Save"));
		/*
		cmdCancel.setText(Msg.getMsg(m_ctx, "Close")+" "+KeyUtils.getKeyStr(getActionKeys().get(GOTO_EXIT)));
		*/
		//cmdEditar.setText(Msg.getMsg(m_ctx, "Edit").replace("&", "")+" "+KeyUtils.getKeyStr(getActionKeys().get(EDIT_PAYMENT)));
		//cmdEliminar.setText(Msg.getMsg(m_ctx, "Delete").replace("&", "")+" "+KeyUtils.getKeyStr(getActionKeys().get(REMOVE_PAYMENT)));
		//cmdGrabar.setText(Msg.getMsg(m_ctx, "Save").replace("&", "")+" "+KeyUtils.getKeyStr(getActionKeys().get(ADD_PAYMENT)));
		//cmdProcess.setText(Msg.getElement(m_ctx, "Processing")+" "+KeyUtils.getKeyStr(getActionKeys().get(GOTO_PROCESS)));

		/*
		
		// Efectivo
		name = VModelHelper.GetReferenceValueTrlFromColumn("C_Order", "PaymentRule", "B", "name");
		jTabbedPane2.setTitleAt(0, name != null ? name : "");
		
		// Transferencia Bancaria
		name = VModelHelper.GetReferenceValueTrlFromColumn("C_Order", "PaymentRule", "Tr", "name");
		jTabbedPane2.setTitleAt(1, name != null ? name : "");
		
		// Cheque
		name = VModelHelper.GetReferenceValueTrlFromColumn("C_Order", "PaymentRule", "S", "name");
		jTabbedPane2.setTitleAt(2, name != null ? name : "");
		
		// Credito
		jTabbedPane2.setTitleAt(3, Msg.translate(m_ctx, "Credit"));
		
		// Pago Adelantado
		jTabbedPane2.setTitleAt(4, getMsg("AdvancedPayment"));
		
		*/
		lblClient.setText(Msg.translate(Env.getCtx(), "AD_Client_ID"));
		lblDocumentNo.setText("Nro. Documento");
        lblOrg.setText(Msg.translate(Env.getCtx(),"AD_Org_ID"));
        lblDocumentType.setText(Msg.translate(Env.getCtx(),"C_DOCTYPE_ID"));
        
        
		lblProject.setText(Msg.translate(Env.getCtx(), "C_Project_ID"));
		lblCurrency.setText(Msg.translate(Env.getCtx(), "C_Currency_ID"));
		lblCampaign.setText(Msg.translate(Env.getCtx(), "C_Campaign_ID"));
		/*
		lblPagoAdelantadoType.setText(getMsg("Type"));
		lblPagoAdelantadoAvailable.setText(Msg.translate(m_ctx, "OpenAmt"));
		
		// Pagos Adelantados
		lblPagoAdelantadoImporte.setText(Msg.getElement(m_ctx, "Amount"));
		lblPagoAdelantado.setText(getMsg("Payment"));
		*/
        updateCaptions();
        
	}
	
	protected void updateCaptions() {
		
		// Traduccion del boton PROCESAR
		// Actualizar las acciones habilitadas de los atajos para cada pestaña
		
		if (jTabbedPane1.getIndex() == 0){
			cmdProcess.setLabel(Msg.translate(Env.getCtx(), "NextStep"));
		}
		else if (jTabbedPane1.getIndex() == 1){
			cmdProcess.setLabel(Msg.translate(Env.getCtx(),"EmitPayment"));
		}
		
		// Las subclases también deben realizar las operaciones necesarias
		// correspondientes en esta instancia
		customUpdateCaptions();
		
	}
	
	protected void clearMediosPago() {
		
		Date d = new Date();
		
		// Efectivo
		
		efectivoLibroCaja.setValue(null);
		txtEfectivoImporte.setText("0");
		
		// Transferencia 
		
		transfCtaBancaria.setValue(null);
		transFecha.setValue(d);
		txtTransfImporte.setText("");
		txtTransfNroTransf.setText("");
		
		// Cheque
		
		chequeChequera.setValue(null);
		chequeFechaEmision.setValue(d);
		chequeFechaPago.setValue(null);
		if (getModel().getBPartner() == null) 
			txtChequeALaOrden.setText("");
		// Modified by Matías Cap -Disytel
		// El campo de cheque a la orden no se limpia cuando se pasan de
		// pestañas, es mas queda la misma descripción para diferentes OP 
		// para distintas entidades comerciales. La modificación involucra que
		// cuando tenemos una entidad comercial entonces coloque el nombre
		// sacando lo que había puesto antes.
		// -------------------------------------------------------------
		// Líneas anteriores comentadas 
		// -------------------------------------------------------------
//		else if (txtChequeALaOrden.getText().equals(""))
//			txtChequeALaOrden.setText(getModel().getBPartner().getName());
		// -------------------------------------------------------------
		else
			txtChequeALaOrden.setText(getModel().getBPartner().getName());
		// -------------------------------------------------------------
		txtChequeImporte.setText("");
		txtChequeNroCheque.setText("");
		txtChequeBanco.setText("");
		txtChequeCUITLibrador.setText("");
		txtChequeDescripcion.setText("");
		
		// Credito
		creditInvoice.setValue(null);
		txtCreditAvailable.setText("");
		txtCreditImporte.setText("");
		
		// Pago anticipado
		pagoAdelantado.setValue(null);
		txtPagoAdelantadoImporte.setText("");
		cashAdelantado.setValue(null);
		txtPagoAdelantadoAvailable.setText("");
		
		// Cheque de tercero
		if (m_chequeTerceroTabIndex >= 0) { // Está disponible la opcion de cheques de tercero
			//chequeTerceroCuenta.setValue(null); No se borra la cuenta para la comodidad del usuario, dado que es un campo de filtro.
			chequeTercero.setValue(null);
			txtChequeTerceroImporte.setText("");
			txtChequeTerceroDescripcion.setText("");
		}
		updatePaymentsTabsState();
	}
	
	protected void loadMedioPago(VOrdenPagoModel.MedioPago mp) {
		
		clearMediosPago();
		
		if (mp.getTipoMP().equals(VOrdenPagoModel.MedioPago.TIPOMEDIOPAGO_EFECTIVO)) { // Efectivo - Cash 
		
			VOrdenPagoModel.MedioPagoEfectivo mpe = (VOrdenPagoModel.MedioPagoEfectivo)mp;
			
			efectivoLibroCaja.setValue(mpe.libroCaja_ID);
			txtEfectivoImporte.setText(m_model.numberFormat(mpe.importe));
			
			jTabbedPane2.setZIndex(TAB_INDEX_EFECTIVO);
			
		} else if (mp.getTipoMP().equals(VOrdenPagoModel.MedioPago.TIPOMEDIOPAGO_TRANSFERENCIA)) { // Transferencia - Transfer
			
			VOrdenPagoModel.MedioPagoTransferencia mpt = (VOrdenPagoModel.MedioPagoTransferencia)mp;
			
			transfCtaBancaria.setValue(mpt.C_BankAccount_ID);
			transFecha.setValue(mpt.fechaTransf);
			txtTransfImporte.setText(m_model.numberFormat(mpt.importe));
			txtTransfNroTransf.setText(mpt.nroTransf);
			
			jTabbedPane2.setZIndex(TAB_INDEX_TRANSFERENCIA);
			
		} else if (mp.getTipoMP().equals(VOrdenPagoModel.MedioPago.TIPOMEDIOPAGO_CHEQUE)) { // Cheque - Check
			
			VOrdenPagoModel.MedioPagoCheque mpc = (VOrdenPagoModel.MedioPagoCheque)mp;
			
			chequeChequera.setValue(mpc.chequera_ID);
			chequeFechaEmision.setValue(mpc.fechaEm);
			chequeFechaPago.setValue(mpc.fechaPago);
			txtChequeALaOrden.setText(mpc.aLaOrden);
			txtChequeImporte.setText(m_model.numberFormat(mpc.importe));
			txtChequeNroCheque.setText(mpc.nroCheque);
			txtChequeBanco.setText(mpc.banco);
			txtChequeCUITLibrador.setText(mpc.cuitLibrador);
			txtChequeDescripcion.setText(mpc.descripcion);
			
			jTabbedPane2.setZIndex(TAB_INDEX_CHEQUE);
		} else if (mp.getTipoMP().equals(VOrdenPagoModel.MedioPago.TIPOMEDIOPAGO_CREDITO)) { // Credito
			VOrdenPagoModel.MedioPagoCredito mpcm = (VOrdenPagoModel.MedioPagoCredito)mp;
			creditInvoice.setValue(mpcm.getC_invoice_ID());
			txtCreditAvailable.setValue(mpcm.getAvailableAmt().toString());
			txtCreditImporte.setValue(mpcm.getImporte().toString());
			
			jTabbedPane2.setZIndex(TAB_INDEX_CREDITO);
		} else if (mp.getTipoMP().equals(VOrdenPagoModel.MedioPago.TIPOMEDIOPAGO_PAGOANTICIPADO)) { // Pago adelantado
			VOrdenPagoModel.MedioPagoAdelantado mpa = (VOrdenPagoModel.MedioPagoAdelantado)mp;
			cboPagoAdelantadoType.setSelectedIndex(PAGO_ADELANTADO_TYPE_PAYMENT_INDEX);
			pagoAdelantado.setValue(mpa.getC_Payment_ID());
			txtPagoAdelantadoImporte.setValue(mpa.getImporte().toString());
			txtPagoAdelantadoAvailable.setValue(getModel().getPagoAdelantadoAvailableAmt(mpa.getC_Payment_ID()).toString());
			
			jTabbedPane2.setZIndex(TAB_INDEX_PAGO_ADELANTADO);
		} else if (mp.getTipoMP().equals(VOrdenPagoModel.MedioPago.TIPOMEDIOPAGO_EFECTIVOADELANTADO)) { // Efectivo adelantado
			VOrdenPagoModel.MedioPagoEfectivoAdelantado mpa = (VOrdenPagoModel.MedioPagoEfectivoAdelantado)mp;
			cboPagoAdelantadoType.setSelectedIndex(PAGO_ADELANTADO_TYPE_CASH_INDEX);
			cashAdelantado.setValue(mpa.getCashLineID());
			txtPagoAdelantadoImporte.setValue(mpa.getImporte().toString());
			txtPagoAdelantadoAvailable.setValue(getModel().getCashAdelantadoAvailableAmt(mpa.getCashLineID()).toString());
			
			jTabbedPane2.setZIndex(TAB_INDEX_PAGO_ADELANTADO);
		} else if (mp.getTipoMP().equals(VOrdenPagoModel.MedioPago.TIPOMEDIOPAGO_CHEQUETERCERO)) { // Cheque de tercero
			VOrdenPagoModel.MedioPagoChequeTercero mpct = (VOrdenPagoModel.MedioPagoChequeTercero)mp;
			chequeTercero.setValue(mpct.getC_Payment_ID());
			txtChequeTerceroImporte.setValue(mpct.getImporte().toString());
			txtChequeTerceroDescripcion.setText(mpct.description);
			
			jTabbedPane2.setZIndex(m_chequeTerceroTabIndex);
		}
			
	}
		
	public void dispose() {
		super.dispose();
		m_model.dispose();
		m_model = null;
		
	}

	@Override
	public void tableChanged(TableModelEvent arg0) {
		// System.out.println("tableChanged: " + arg0);
		if ( (arg0.getColumn() == m_model.m_facturasTableModel.getColumnCount() - 1) || (arg0.getColumn() == m_model.m_facturasTableModel.getColumnCount() - 2) ){
			// Se actualizó el monto manual
			for (int row = arg0.getFirstRow(); row <= arg0.getLastRow() && row < m_model.m_facturas.size(); row++) {
				ResultItemFactura rif = (ResultItemFactura)m_model.m_facturas.get(row);
				int currency_ID_To = (Integer) m_model.m_facturas.get(row).getItem(m_model.m_facturasTableModel.getCurrencyColIdx());
				if (arg0.getColumn() == m_model.m_facturasTableModel.getColumnCount() - 1){
					m_model.actualizarPagarConPagarCurrency(row,rif,currency_ID_To);
				}
				else{
					m_model.actualizarPagarCurrencyConPagar(row,rif,currency_ID_To);
				}
				m_model.m_facturasTableModel.fireTableDataChanged();	
			}
			resetModel();
		}
	}

	public void valueChange(ValueChangeEvent e) {
		// System.out.println("vetoableChange: " + arg0);
		if (e.getSource() == BPartnerSel) {
			
			// m_model.setBPartnerFacturas((Integer)BPartnerSel.getValue());
			
//			SwingUtilities.invokeLater( new Runnable() {
//	            public void run() {
	            	// Actualizo el modelo. Utilizo newValueOnChange, dado que si utilizo newValue,
					// obtengo null (o el valor viejo) en este punto del código
	            	getModel().updateBPartner((Integer)BPartnerSel.getNewValueOnChange());
					// Actualizo los componentes custom de la interfaz gráfica
					// relacionados con el cambio de la entidad comercial
	            	customUpdateBPartnerRelatedComponents(true);
	            	buscarPagos();
	            	// Actualizar interfaz grafica para null value
					if (BPartnerSel.getNewValueOnChange() == null)
						this.cmdProcess.setEnabled(false); //cmdBPartnerSelActionPerformed(null);
	            	updatePayAllInvoices(false);
//	            }
//	        } );			
		} else if (e.getSource() == cboCurrency) {
			updateDependent();
		} else if (e.getSource() == efectivoLibroCaja) {
			
		} else if (e.getSource() == transfCtaBancaria) {
			
		} else if (e.getSource() == chequeChequera) {
			chequeraChange(e);
		} else if (e.getSource() == invoiceDatePick) {
			
			onFechaChange(false);
			
		} else if (e.getSource() == cboOrg) {
			int AD_Org_ID = (Integer)e.getNewValue();
			updateOrg(AD_Org_ID);
		
		} else if (e.getSource() == cboDocumentType) {
			if(e.getNewValue() != null){
				m_model.setDocumentType((Integer)e.getNewValue());
				seq = MSequence.get(m_ctx, getSeqName(), false, Env.getAD_Client_ID(m_ctx));
				fldDocumentNo.setValue(seq.getCurrentNext().toString());
			}
			else{
				fldDocumentNo.setValue(null);
				m_model.setDocumentType(null);
			}
		}
	}

	private void updateDependent() {
		efectivoLibroCaja.setValue(null);
	}
/*
	public void stateChanged(ChangeEvent arg0) {
		if (arg0.getSource() == jTabbedPane1) {
			// TAB principal
			if (!m_cambioTab && jTabbedPane1.getSelectedIndex() == 1) {
				jTabbedPane1.setSelectedIndex(0);
			}
			
			updateCaptions();
				
			BPartnerSel.setReadWrite(jTabbedPane1.getSelectedIndex() == 0);
			cboOrg.setReadWrite(jTabbedPane1.getSelectedIndex() == 0);
			cboDocumentType.setReadWrite(jTabbedPane1.getSelectedIndex() == 0);
			fldDocumentNo.setReadWrite(jTabbedPane1.getSelectedIndex() == 0);
			
		} else if (arg0.getSource() == jTabbedPane2) {
			// TAB de medios de pago
			updateContextValues();
		} else {
			// System.out.println("stateChanged: " + arg0);
		}
	}

	private void treeUpdated() {
		
		// Expand all tree nodes 
		
		SwingUtilities.invokeLater( new Runnable() {
            public void run() {
            	for (int i = 0; i < jTree1.getRowCount(); i++)
            		jTree1.expandRow(i);
            }
        } );
		
		// Update stats text fields
		updateSummaryInfo();
	}
	*/
	/**
	 * Actualización de la organización
	 * @param AD_Org_ID id de la organización nueva
	 */
    
	protected void updateOrg(Integer AD_Org_ID){
		getModel().updateOrg(AD_Org_ID);
    	updatePayAllInvoices(false);
	}
	
	
	/**
	 * Actualización de la información de resumen de pagos, saldo, retenciones,
	 * etc.
	 */
    
	protected void updateSummaryInfo(){
		BigDecimal sumaMediosPago = m_model.getSumaMediosPago();
		
		txtSaldo.setText(numberFormat(m_model.getSaldoMediosPago()));
		txtDifCambio.setText(numberFormat(getModel().calculateExchangeDifference()));
		txtTotalPagar2.setText(numberFormat(m_model.getSumaTotalPagarFacturas()));
		txtRetenciones2.setText(numberFormat(m_model.getSumaRetenciones()));
		txtMedioPago2.setText(numberFormat(sumaMediosPago));
		
		cboProject.setReadWrite(sumaMediosPago.signum() == 0);
		cboCampaign.setReadWrite(sumaMediosPago.signum() == 0);
	}

	protected String numberFormat(BigDecimal nn) {
		return m_model.numberFormat(nn);
	}
	
	protected BigDecimal numberParse(String nn) throws ParseException {
		return m_model.numberParse(nn);
	}
	
	protected void tableUpdated() {
		updateTotalAPagar1();
	}
	
	protected void validateConversionRate() {
		if (!m_model.validateConversionRate()){
			showError("@NoCurrencyConvertError@");
		}
	}

	protected void setModel(VOrdenPagoModel model) {
		m_model = model;
	}
	
	protected VOrdenPagoModel getModel() {
		return m_model;
	}
	
	protected WTableDirEditor createChequeChequeraLookup() {
		MLookupInfo info = VComponentsFactory.MLookupInfoFactory( Env.getCtx(),m_WindowNo, 0, 6188, DisplayType.TableDir, m_model.getChequeChequeraSqlValidation());
		MLookup lookup = new MLookup(info, 0);
		return new WTableDirEditor("C_BankAccountDoc_ID", false, false, true, lookup);
	}

	protected WSearchEditor createChequeBancoIDLookup() {
		MLookupInfo info = VComponentsFactory.MLookupInfoFactory( Env.getCtx(),m_WindowNo, 0, 3031, DisplayType.Search, null);
		MLookup lookup = new MLookup(info, 0);
		return new WSearchEditor("C_Bank_ID", false, false, true, lookup);
	}
	
	protected void chequeraChange(ValueChangeEvent e) {
		Integer C_BankAccountDoc_ID = (Integer) e.getNewValue();
		if(C_BankAccountDoc_ID != null && C_BankAccountDoc_ID > 0) {
			X_C_BankAccountDoc bankAccountDoc = new X_C_BankAccountDoc(Env.getCtx(),C_BankAccountDoc_ID,null);
			int nextNroCheque = bankAccountDoc.getCurrentNext();
			txtChequeNroCheque.setText(String.valueOf(nextNroCheque));
		} else
			txtChequeNroCheque.setText("");
	}

	/**
	 * @return the actualizarNrosChequera
	 */
 
	protected boolean isActualizarNrosChequera() {
		return actualizarNrosChequera;
	}
	
	/**
	 * @param actualizarNrosChequera the actualizarNrosChequera to set
	 */
	protected void setActualizarNrosChequera(boolean actualizarNrosChequera) {
		this.actualizarNrosChequera = actualizarNrosChequera;
	}
	
	/**
	 * Redefinir en caso de ser nesario ampliar el conjunto de pestañas con medios de
	 * pago. Aquí se deben agregar las pestañas necesarias por las especializaciones.
	 * @param tabbedPane Panel de pestaña que contiene los medios de pagos.
	 */
	protected void addCustomPaymentTabs(Tabpanel tabbedPane) { 
		// Agregado de pestaña de medio de pago cheques de terceros.
//		tabbedPane.addTab(getMsg("ThirdPartyCheck"), createChequeTerceroTab());
		tabbedPane.appendChild(createChequeTerceroTab());
		// FEDE:TODO		
//		m_chequeTerceroTabIndex = tabbedPane.indexOfComponent(panelChequeTercero);
	}
	
	/**
	 * Redefinir en caso que de ser necesario ampliar la funcionalidad y
	 * operaciones luego de crear pestañas custom si hubiere.
	 */
	protected void addCustomOperationAfterTabsDefinition(){
		// Incorporación de operaciones luego de la definición de las pestañas
		// custom
	}
	
	/**
	 * Guardado de medios de pago específicos de las subclases. En caso de que se intente
	 * guardar un medio de pago que no es de esta clase, entonces se invoca este método
	 * el cual debe implementar la lógica de guardado del medio de pago indicado por
	 * el tabIndex.
	 * @param tabIndex Indice de pestaña que contiene los datos del medio de pago.
	 */
    
	protected void cmdCustomSaveMedioPago(int tabIndex) throws Exception { 
		if (tabIndex == m_chequeTerceroTabIndex)
			saveChequeTerceroMedioPago();
	}
	
	protected Integer getC_Campaign_ID() {
		return (Integer)cboCampaign.getValue();
	}
	
	protected Integer getC_Project_ID() {
		return (Integer)cboProject.getValue();
	}
	/*
	protected boolean canEditTreeNode(VOrdenPagoModel.MyTreeNode treeNode) {
		return treeNode.isMedioPago();
	}
	*/
	/**
	 * Ingresa en modo de edición el medio de pago seleccionado en el árbol.
	 */
    /*
	protected void cmdEditMedioPago(VOrdenPagoModel.MyTreeNode tn) {
		VOrdenPagoModel.MedioPago mp = (VOrdenPagoModel.MedioPago)tn.getUserObject();
		
		if (mp == null)
			return;
		
		if (tn.isMedioPago()) {
			m_model.removeMedioPago(mp);
			loadMedioPago(mp);
		}
	}
	*/
	/**
	 * Borrado del nodo actual del arbol de medios de pago y retenciones.
	 */
    /*
	protected void cmdDeleteMedioPago(VOrdenPagoModel.MyTreeNode tn) {
		VOrdenPagoModel.MedioPago mp = (VOrdenPagoModel.MedioPago)tn.getUserObject();
		
		if (mp == null)
			return;
		
		if (tn.isMedioPago()) {
			if (confirmDeleteMP(mp)){
				m_model.removeMedioPago(mp);
				updatePayAmt(getModel().getSaldoMediosPago());
			}
		}
	}
	
	protected boolean confirmDeleteMP(Object mp) {
		String msg = Msg.parseTranslation(m_ctx, "@DeleteRecord?@\r\n" + mp.toString());
		String title = Msg.getMsg(m_ctx, "Delete"); 
		
		// TODO: VER
		//return (JOptionPane.showConfirmDialog(this, msg, title, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
		return false;
	}
*/	
	protected String getMsg(String name) {
		return Msg.translate(m_ctx, name);
	}
	
	protected void updatePaymentsTabsState() {
//		jTabbedPane2.setEnabledAt(TAB_INDEX_CREDITO, m_model.isNormalPayment());
//		jTabbedPane2.setEnabledAt(TAB_INDEX_PAGO_ADELANTADO, m_model.isNormalPayment());
		jTabbedPane2.setEnabled(m_model.isNormalPayment());
		
		// Refrescar el monto de la pestaña con el total a pagar
		updatePayAmt(getModel().getSaldoMediosPago());
//		jTabbedPane2.setSelectedIndex(TAB_INDEX_EFECTIVO);
	}
	
	protected void updatePagoAdelantadoTab() {
//		pagoAdelantadoTypePanel.removeAll();
		pagoAdelantado.setValue(null);
		cashAdelantado.setValue(null);
		txtPagoAdelantadoAvailable.setText("");
		if (cboPagoAdelantadoType.getSelectedIndex() == PAGO_ADELANTADO_TYPE_PAYMENT_INDEX) {
//			pagoAdelantadoTypePanel.add(pagoAdelantado);
			lblPagoAdelantado.setText(getMsg("Payment"));
		} else if (cboPagoAdelantadoType.getSelectedIndex() == PAGO_ADELANTADO_TYPE_CASH_INDEX) {
//			pagoAdelantadoTypePanel.add(cashAdelantado);
			lblPagoAdelantado.setText(getMsg("Cash"));
		}
	}
	
	private Panel createChequeTerceroTab() {
		panelChequeTercero = new Panel();
		
		// Cuenta
		lblChequeTerceroCuenta = new Label();
		lblChequeTerceroCuenta.setText(getMsg("Account"));
		MLookupInfo info = VComponentsFactory.MLookupInfoFactory( Env.getCtx(),m_WindowNo, 0, 5283, DisplayType.Search, m_model.getChequeTerceroCuentaSqlValidation());
		Lookup lookup = new MLookup(info, 0);
		chequeTerceroCuenta = new WSearchEditor("C_BankAccount_ID", false, false, true, lookup);
        
        chequeTerceroCuenta.addValueChangeListener(new ValueChangeListener() {
			public void valueChange(ValueChangeEvent evt) {
	        		Integer bankAccountID = (Integer)chequeTerceroCuenta.getValue();
	        		if (bankAccountID == null)
	        			bankAccountID = 0;
	        		Env.setContext(m_ctx, m_WindowNo, "C_BankAccount_ID", bankAccountID);
			}
		});
        chequeTerceroCuenta.setValue(null);
		// Cheque
        lblChequeTercero = new Label();
        lblChequeTercero.setText(getMsg("Check"));
		info = VComponentsFactory.MLookupInfoFactory( Env.getCtx(),m_WindowNo, 0, 5043, DisplayType.Search, m_model.getChequeTerceroSqlValidation());
		lookup = new MLookup(info, 0);
		chequeTercero = new WSearchEditor("C_Payment_ID", false, false, true, lookup);
        
        chequeTercero.addValueChangeListener(new ValueChangeListener() {
			public void valueChange(ValueChangeEvent evt) {
				Integer paymentID = (Integer)chequeTercero.getValue();
				String importe = "";
				if (paymentID != null)
					importe = getModel().numberFormat(getModel().getChequeAmt(paymentID));
				txtChequeTerceroImporte.setText(importe);			
			}
		}); 
        // Importe
        lblChequeTerceroImporte = new Label();
        lblChequeTerceroImporte.setText(Msg.getElement(m_ctx, "Amount"));
        txtChequeTerceroImporte = new Textbox();
        txtChequeTerceroImporte.setText("0");
//        initFormattedTextField((JFormattedTextField)txtChequeTerceroImporte);
        txtChequeTerceroImporte.setValue(null);
        txtChequeTerceroImporte.setReadonly(true); // Editable(false);
        // Descripcion
        lblChequeTerceroDescripcion = new Label();
        lblChequeTerceroDescripcion.setText(getMsg("Description"));
        txtChequeTerceroDescripcion = new Textbox();
		
        // TODO:FEDE armar bien el panel
        
		return panelChequeTercero;
	}
	
	private void saveChequeTerceroMedioPago() throws Exception {
		Integer paymentID = (Integer)chequeTercero.getValue();
		BigDecimal importe; 
		Integer monedaOriginalID;
		try {
			monedaOriginalID = (Integer) cboCurrency.getValue();
		} catch (Exception e) {
			throw new Exception(cboCurrency.getValue().toString());
		}
		try {
			importe = numberParse(txtChequeTerceroImporte.getText());
		} catch (Exception e) {
			throw new Exception(lblChequeTerceroImporte.getValue());
		}
		String description = txtChequeTerceroDescripcion.getText().trim();
		getModel().addChequeTercero(paymentID, importe, description, monedaOriginalID);
	}
	
	private void updateContextValues() {
		if (jTabbedPane2.getIndex() == m_chequeTerceroTabIndex) {
			setIsSOTrxContext("Y");
			setBPartnerContext(null);
		} else {
			setIsSOTrxContext();
			setBPartnerContext();
		}
		updatePaymentsTabsState();
	}
	
	private void setIsSOTrxContext(String value) {
		Env.setContext(m_ctx,m_WindowNo,"IsSOTrx", value);
	}
	
	private void setIsSOTrxContext() {
		setIsSOTrxContext(getModel().getIsSOTrx());
	}
	
	private void setBPartnerContext(Integer bPartnerID) {
		if (bPartnerID != null)
			Env.setContext(m_ctx, m_WindowNo, "C_BPartner_ID", bPartnerID);
		else
			Env.setContext(m_ctx, m_WindowNo, "C_BPartner_ID", (String)null);
	}
	
	private void setCurrencyContext(Integer currencyID) {
		if (currencyID != null){
			Env.setContext(m_ctx, m_WindowNo, "C_Currency_ID", currencyID);
			// Es necesario setear el Currency_Id a 0 ya que al querer utilizarlo en alguna consulta de filtro para un VLookUp lo busca con m_WindowNo 0.
			Env.setContext(m_ctx, 0, "C_Currency_ID", currencyID);
		}
		else
			Env.setContext(m_ctx, m_WindowNo, "C_Currency_ID", (String)null);
	}
	
	private void setBPartnerContext() {
		Integer value = 0;
		if (BPartnerSel.getValue() != null)
			value = (Integer)BPartnerSel.getValue(); 
		setBPartnerContext(value);
	}
	
	private void setCurrencyContext() {
		Integer value = 0;
		if (cboCurrency.getValue() != null)
			value = (Integer) cboCurrency.getValue(); 
		setCurrencyContext(value);
	}
	
	/**
	 * Busca las notas de créditos o pagos anticipados sin imputar para la
	 * entidad comercial seleccionada
	 */
    
	private void buscarPagos() {
		String title = Msg.getMsg(m_ctx, "InfoPayment");
		Integer value = 0;
		if (BPartnerSel.getValue() != null) {
			value = (Integer) BPartnerSel.getValue();
			if (getModel().buscarPagos(value) == true) {
				showInfo("El Proveedor tiene notas de crédito o pagos anticipados sin imputar");
			}
		}
	}

	private void viewDescription() {		
		txtDescription.setText("");
		Integer value = 0;
		if (BPartnerSel.getValue() != null) {
			value = (Integer) BPartnerSel.getValue();
			MBPartner bpartner = new MBPartner(m_ctx, value.intValue(), null);			
			if (bpartner.getDescription() != null) {
				if (bpartner.getDescription().compareTo("") != 0) {
					String description=bpartner.getDescription();					
					getModel().setDescription(description);
					txtDescription.setText(getModel().getDescription());
				}
			}
		}
	}
	
	/**
	 * Actualizar el total a pagar de la primer pestaña
	 */    
	protected void updateTotalAPagar1(){
		txtTotalPagar1.setText(numberFormat(m_model.getSumaTotalPagarFacturas()));
	}
	
	/**
	 * Actualiza componentes custom de la interfaz gráfica relacionadas con el
	 * cambio de entidad comercial
	 */
    
	protected void customUpdateBPartnerRelatedComponents(boolean loadingBP){
		if(loadingBP==true)
		{	
			viewDescription();	
		}
		// Por ahora aca no se hace nada, verificar subclases
	}
	
	protected void updatePayAmt(BigDecimal amt){
		int currencyID = ( (Integer) cboCurrency.getValue() == null) ? m_C_Currency_ID : (Integer) cboCurrency.getValue();

		amt = MCurrency.currencyConvert(amt, m_C_Currency_ID, currencyID, new Timestamp(System.currentTimeMillis()), getModel().AD_Org_ID, m_ctx);
		
		Integer tabIndexSelected = jTabbedPane2.getIndex();
		if(tabIndexSelected.equals(TAB_INDEX_CHEQUE)){
			txtChequeImporte.setValue(amt.toString());
		}
		else if(tabIndexSelected.equals(TAB_INDEX_CREDITO)){
			txtCreditImporte.setValue(amt.toString());
		}
		else if(tabIndexSelected.equals(TAB_INDEX_EFECTIVO)){
			txtEfectivoImporte.setValue(amt.toString());
		}
		else if(tabIndexSelected.equals(TAB_INDEX_PAGO_ADELANTADO)){
			txtPagoAdelantadoImporte.setValue(amt.toString());
		}
		else if(tabIndexSelected.equals(TAB_INDEX_TRANSFERENCIA)){
			txtTransfImporte.setValue(amt.toString());
		}
		else {
			updateCustomPayAmt(amt);
		}
	}
	
	protected void updateCustomPayAmt(BigDecimal amt){
		// Por ahora aca no se hace nada, verificar subclases
	}
	
	
	/**
	 * Actualizo componentes luego del preprocesar y antes de procesar.
	 */
	protected void updateComponentsPreProcesar(){
		// Por ahora aca no se hace nada, verificar subclases		
	}
	/**
	 * Actualiza componentes de interfaz gráfica luego de agregar o eliminar un
	 * medio de pago
	 * 
	 * @param recibe
	 *            la acción que se realizó sobre el medio de pago, las acciones
	 *            pueden ser inserción, edición y eliminación, valores
	 *            referenciados en {@link VOrdenPago#MEDIOPAGO_ACTION_INSERT},
	 *            {@link VOrdenPago#MEDIOPAGO_ACTION_EDIT} y
	 *            {@link VOrdenPago#MEDIOPAGO_ACTION_DELETE}.
	 */
	protected void updateCustomInfoAfterMedioPago(Integer medioPagoAction){
		// Por ahora aca no se hace nada, verificar subclases
	}
	/**
	 * Realizar operaciones antes del pro-procesar
	 */   
	protected void makeOperationsBeforePreProcesar() throws Exception{
		// Por ahora no hace nada aquí
	}
	
	/**
	 * Realizar operaciones luego de cambiar el tipo de pago, normal o
	 * adelantado
	 */
	protected void updateCustomTipoPagoChange(){
		// Por ahora no hace nada aquí
	}
	
	/**
	 * Realizar operaciones luego de iniciar los atajos y sus operaciones
	 */
	protected void customKeyBindingsInit(){
		// Por ahora no hace nada aquí		
	}
	
	/**
	 * Realizar operaciones luego de actualizar los captions y acciones
	 */
	protected void customUpdateCaptions(){
		// Por ahora no hace nada aquí
	}
	/**
	 * Resetear info.
	 */
	protected void reset(){
		BPartnerSel.setValue(null);
		m_model.setBPartnerFacturas(0);
		radPayTypeStd.setSelected(true);
		m_model.actualizarFacturas();
		cboCampaign.setValue(null);
		cboProject.setValue(null);
		cboCurrency.setValue(m_C_Currency_ID);
		txtTotalPagar1.setValue(null);
		m_cambioTab = true;
		tabbox.setSelectedIndex(0);
		m_cambioTab = false;
		txtDescription.setText("");
		m_model.setDescription("");
		checkPayAll.setSelected(false);
		// actualizar secuencia
		seq.setCurrentNext(seq.getCurrentNext().add(BigDecimal.ONE));
		seq.save();
		fldDocumentNo.setValue(seq.getCurrentNext().toString());
		
		m_model.setDocumentNo("");
		getModel().reset();
	}
	
	protected String getSeqName()
	{
		if (m_model.getDocumentType() != null){
			return DB.getSQLValueString( null,"SELECT s.name FROM AD_Sequence s INNER JOIN C_DocType d ON (s.AD_Sequence_ID = d.docnosequence_ID) WHERE C_DocType_ID =?",m_model.getDocumentType());
		}
		return null;
		
	}

	/**
	 * Realiza el movimiento hacia adelante o atrás de la selección de una
	 * grilla.
	 * 
	 * @param forward
	 *            <code>true</code> para avanzar una fila, <code>false</code>
	 *            para retroceder.
	 */
    /*
	private void moveTableSelection(JTable table, boolean forward) {
		if (table.getRowCount() == 0) {
			return;
		}
		int srow = table.getSelectedRow();
		if (srow == -1) {
			srow = 0;
		} else {
			srow = forward ? srow+1 : srow-1;
			if (srow < 0) {
				srow = table.getRowCount() - 1;
			} else if (srow >= table.getRowCount()) {
				srow = 0;
			}
		}
		table.requestFocus();
		table.setRowSelectionInterval(srow, srow);
		table.setColumnSelectionInterval(table.getColumnCount()-1, table.getColumnCount()-1);
	}
	*/
	/**
	 * Dispara el evento action performed con el evento parámetro a todos los
	 * listeners parámetro
	 * 
	 * @param listeners
	 * @param event
	 */
    /*
	protected void fireActionPerformed(ActionListener[] listeners, ActionEvent event){
		for (ActionListener actionListener : listeners) {
			actionListener.actionPerformed(event);
		}
	}
	*/
    
	@Override
	protected void initForm() {

		try
		{
			
			setIsSOTrxContext();
			
	        if (Env.getAD_Org_ID(Env.getCtx()) == 0) {
	        	showError("@InvalidPORCOrg@");
	        	return;
        	};
			
			initComponents();
			zkInit();
			initTranslations();
			dynInit();
			customInitComponents();
			getModel().m_facturasTableModel.addTableModelListener(this);
			
			onTipoPagoChange(false);
			
		}
		catch(Exception e)
		{
			log.log(Level.SEVERE, "init", e);
		}
	}


	private void dynInit() {
		// TODO Auto-generated method stub
		
	}


	private void zkInit() {
		Borderlayout layout = new Borderlayout();
		layout.setHeight("100%");
		layout.setWidth("100%");
		this.appendChild(layout);
        
        North north = new North();
		layout.appendChild(north);
		north.appendChild(jPanel1);
		
		Rows rows = jPanel1.newRows();
		Row row = rows.newRow();
		row.appendChild(lblClient.rightAlign());
		row.appendChild(cboClient.getComponent());
		
		row.appendChild(new Space());
		row.appendChild(lblOrg.rightAlign());
		row.appendChild(cboOrg.getComponent());
		row.appendChild(new Space());
		
		row = rows.newRow();
		row.appendChild(lblBPartner.rightAlign());
		row.appendChild(BPartnerSel.getComponent());
		row.appendChild(new Space());
		row.appendChild(lblDocumentNo.rightAlign());
		row.appendChild(fldDocumentNo);
		row.appendChild(new Space());
		
		row = rows.newRow();
		row.appendChild(lblDescription.rightAlign());
		row.appendChild(txtDescription);
		txtDescription.setWidth("100%");
		row.appendChild(new Space());

		row.appendChild(lblDocumentType.rightAlign());
		row.appendChild(cboDocumentType.getComponent());
		row.appendChild(new Space());
		
		Center center = new Center();
		layout.appendChild(center);
		center.appendChild(tabbox);
		
		tabbox.setHeight("100%");
		tabbox.appendChild(tabs);
		tabbox.appendChild(tabpanels);
		
		createPaymentSelectionTab();
		createPaymentTab();
		
		Tab tabPaymentSelection = new Tab(Msg.getMsg(Env.getCtx(), "PaymentSelection"));
		tabpanels.appendChild(jTabbedPane1);
		tabs.appendChild(tabPaymentSelection);
		
		Tab tabPaymentRule = new Tab(Msg.getMsg(Env.getCtx(), "PaymentRule"));
		tabpanels.appendChild(jTabbedPane2);
		tabs.appendChild(tabPaymentRule);
		
		South south = new South();
		layout.appendChild(south);
		Div divButton = new Div();
		divButton.setAlign("end");
		divButton.appendChild(cmdProcess);
		south.appendChild(divButton);
		
	}

	
	private Panel agregarCampProy() {
		
		Panel panel = new Panel();
		Panelchildren panelchildren = new Panelchildren();
		//panelchildren.setStyle("border: 1px solid red");
		
		Grid gridpanel = GridFactory.newGridLayout();
		gridpanel.setWidth("100%");
		
		Rows rows = gridpanel.newRows();
		Row row = rows.newRow();
		row.appendChild(lblCampaign.rightAlign());
		row.appendChild(cboCampaign.getComponent());
		
		//row = rows.newRow();
		row.appendChild(lblProject.rightAlign());
		row.appendChild(cboProject.getComponent());
		
		row = rows.newRow();
		row.appendChild(lblCurrency.rightAlign());
		row.appendChild(cboCurrency.getComponent());
		
		panelchildren.appendChild(gridpanel);
		panel.appendChild(panelchildren);
        
        return panel;
	}
	
private Panel agregarTree() {
		
		Panel panel = new Panel();
		Panelchildren panelchildren = new Panelchildren();
		
		//panelchildren.setStyle("border: 1px solid red");
		
		Treeitem treeitem1 = new Treeitem("Prueba 1");
		
		Treeitem treeitem3 = new Treeitem("Prueba 3");
		Treeitem treeitem4 = new Treeitem("Prueba 4");
		Treechildren treechildren1 = new Treechildren();
		treechildren1.appendChild(treeitem3);
		treechildren1.appendChild(treeitem4);
		
		Treeitem treeitem2 = new Treeitem("Prueba 2");
		treeitem2.appendChild(treechildren1);
		
		Treechildren treechildren = new Treechildren();
		treechildren.appendChild(treeitem1);
		treechildren.appendChild(treeitem2);
		
		Tree tree = new Tree();
		tree.setRows(15);
		tree.appendChild(treechildren);
		
		panelchildren.appendChild(tree);
		panelchildren.appendChild(cmdEliminar);
		panelchildren.appendChild(cmdEditar);
		
		panel.appendChild(panelchildren);
        return panel;
	}

	private Panel agregarTabs() {
		
		Panel panel = new Panel();
		Panelchildren panelchildren = new Panelchildren();
		//panelchildren.setStyle("border: 1px solid red");
		
		Tabpanel tabpanel1 = new Tabpanel();
	    Tabpanel tabpanel2 = new Tabpanel();
	    Tabpanel tabpanel3 = new Tabpanel();
	    Tabpanel tabpanel4 = new Tabpanel();
	    //Tabpanel tabpanel5 = new Tabpanel();
	    Tabpanel tabpanel6 = new Tabpanel();
	    
	    tabpanel1.setHeight("150px");
	    tabpanel2.setHeight("150px");
	    tabpanel3.setHeight("150px");
	    tabpanel4.setHeight("150px");
	    //tabpanel5.setHeight("150px");
	    tabpanel6.setHeight("150px");
	    
	    
	    Tabpanels tabpanels = new Tabpanels();
	    tabpanels.appendChild(tabpanel1);
	    tabpanels.appendChild(tabpanel2);
	    tabpanels.appendChild(tabpanel3);
	    tabpanels.appendChild(tabpanel4);
	    tabpanels.appendChild(createCashTab());
	    tabpanels.appendChild(tabpanel6);
	 	
	    Tab tab1 = new Tab("Pago Adelantado");
	    Tab tab2 = new Tab("Cheque de Tercero");
	    Tab tab3 = new Tab("Cheque o Talón");
	    Tab tab4 = new Tab("Crédito");
	    Tab tab5 = new Tab("Efectivo");
	    Tab tab6 = new Tab("Transferencia Bancaria");
		 
	    Tabs tabs = new Tabs();
	    tabs.appendChild(tab1);
	    tabs.appendChild(tab2);
	    tabs.appendChild(tab3);
	    tabs.appendChild(tab4);
	    tabs.appendChild(tab5);
	    tabs.appendChild(tab6);
	 	
	    Tabbox tabbox = new Tabbox();
	    tabbox.setMold("accordion");;
	    tabbox.setHeight("100%");
		tabbox.appendChild(tabs);
		tabbox.appendChild(tabpanels);
	 	
		panelchildren.appendChild(tabbox);
		panel.appendChild(panelchildren);
	    
	    return panel;
	}


	private void createPaymentSelectionTab() {
		Hbox contenedor1 = new Hbox();
		contenedor1.setWidth("100%");
		//contenedor1.setStyle("border: 1px solid red");
		
		Div divButtonGroup1 = new Div();
		//caja1.setStyle("border: 1px solid red");
		divButtonGroup1.appendChild(buttonGroup1);
		
		Div divCheckPayAll = new Div();
		divCheckPayAll.setAlign("end");
		//caja2.setStyle("border: 1px solid red");
		divCheckPayAll.appendChild(checkPayAll);
		
		contenedor1.appendChild(divButtonGroup1);
		contenedor1.appendChild(divCheckPayAll);
		jTabbedPane1.appendChild(contenedor1);
		
		jTabbedPane1.appendChild(new Separator());
	
		jTabbedPane1.appendChild(tblFacturas);
		
		jTabbedPane1.appendChild(new Separator());
		
		Hbox contenedor2 = new Hbox();
		contenedor2.setWidth("100%");
		//contenedor1.setStyle("border: 1px solid red");
		
		Div divButtonGroup2 = new Div();
		//divButtonGroup2.setStyle("border: 1px solid red");
		divButtonGroup2.appendChild(buttonGroup2);
		divButtonGroup2.appendChild(invoiceDatePick);
		
		Div divTxtEfectivoImporte = new Div();
		divTxtEfectivoImporte.setAlign("end");
		//divTxtEfectivoImporte.setStyle("border: 1px solid red");
		divTxtEfectivoImporte.appendChild(lblTotalPagar1);
		divTxtEfectivoImporte.appendChild(txtTotalPagar1);
		
		contenedor2.appendChild(divButtonGroup2);
		contenedor2.appendChild(divTxtEfectivoImporte);
		jTabbedPane1.appendChild(contenedor2);
	}
	
	
	/**
	 * Fuerza el reseteo del modelo de la Grid en base a los datos del modelo de VOrdenPagoModel
	 */
	protected void resetModel() {
		listModel = new FacturasModel(VModelHelper.HideColumnsTableModelFactory(m_model.m_facturasTableModel), m_WindowNo);
		tblFacturas.setModel(listModel);
		updateTotalAPagar1();
	}
	
	/**
	 * Encargada de renderizar la grilla de facturas a pagar
	 */
	public static class GridRenderer implements RowRenderer {

		WOrdenPago owner = null;
		Columns cols = new Columns();

		public GridRenderer(WOrdenPago owner) {
			this.owner = owner;
		}
		
		@Override
		public void render(org.zkoss.zul.Row arg0, Object arg1) throws Exception {	
			// Si no hay modelo, nada para dibujar
			if (owner.listModel == null)
				return;
			// Si no hay columnas, nada para dibujar
			if (owner.listModel.getColumnCount() == 0)
				return;

			// Resetear las columnas
			owner.tblFacturas.removeChild(cols);
			cols = new Columns();
			int colCount = owner.listModel.getColumnCount();
			for (int i=0; i < colCount; i++) {
				Column col = new Column();
				col.setLabel(owner.listModel.getColumnName(i));
				cols.appendChild(col);
			}
			owner.tblFacturas.appendChild(cols);		
			
			// Setear la fila
			Object[] _data = (Object[])arg1;
			for (int i = 0; i < colCount; i++) {
				// Las dos ultimas columnas son para seteo de datos 
				if (owner.listModel.model.isCellEditable(1, i) && !owner.checkPayAll.isChecked()) {
					Textbox aTextbox = new Textbox();
					aTextbox.setValue(_data[i].toString()); 
					aTextbox.setWidth("60px");
					aTextbox.setParent(arg0);
					// Setear toPay (anteultima columna) hacia toPayCurrency (ultima columna)
					if (i == colCount - 2) {
						aTextbox.addEventListener(Events.ON_OK, new EventListener() {
							@Override
							public void onEvent(Event evt) throws Exception {
								toPay2toPayCurrency();
							}
						});
					}
					// Setea toPayCurrency (ultima columna) hacia toPay (anteultima columna)
					if (i == colCount - 1) {
						aTextbox.addEventListener(Events.ON_OK, new EventListener() {
							@Override
							public void onEvent(Event evt) throws Exception {
								toPayCurrency2toPay();
							}
						});
					}
				} 
				else {
					Label aLabel = new Label(_data[i].toString()); 
					aLabel.setParent(arg0);
				}
			}

		}
		
		/**
		 * Setea toPay (anteultima columna) hacia toPayCurrency (ultima columna) 
		 */
		protected void toPay2toPayCurrency() {
			int rows = owner.listModel.model.getRowCount(); 
			int cols = owner.listModel.model.getColumnCount();
			ArrayList<BigDecimal> values = new ArrayList<BigDecimal>();
			// Recuperar valores de la columna toPay a partir del Textbox
			for (int row = 0; row < rows; row++) {
				BigDecimal newValue = new BigDecimal(0);
				try {
					newValue = new BigDecimal(((Textbox)owner.tblFacturas.getCell(row, cols - 2)).getValue());
				}
				catch (Exception e) { }
				values.add(newValue);
			}
			// Setear valores en el modelo
			for (int row = 0; row < rows; row++) {
				((FacturasModel)owner.tblFacturas.getModel()).model.setValueAt(values.get(row), row, cols - 2);
			}
			// Invocar al metodo para actualizar toPayCurrency
			for (int row = 0; row < rows; row++) {
				ResultItemFactura rif = (ResultItemFactura)owner.getModel().m_facturas.get(row);
				int currency_ID_To = (Integer)owner.getModel().m_facturas.get(row).getItem(owner.getModel().m_facturasTableModel.getCurrencyColIdx());
				owner.getModel().actualizarPagarCurrencyConPagar(row,rif,currency_ID_To);
			}
			owner.resetModel();
		}
		
		/**
		 * Setea toPayCurrency (ultima columna) hacia toPay (anteultima columna) 
		 */
		protected void toPayCurrency2toPay() {
			int rows = owner.listModel.model.getRowCount(); 
			int cols = owner.listModel.model.getColumnCount();
			ArrayList<BigDecimal> values = new ArrayList<BigDecimal>();
			// Recuperar valores de la columna toPayCurrency  a partir del Textbox
			for (int row = 0; row < rows; row++) {
				BigDecimal newValue = new BigDecimal(0);
				try {
					newValue = new BigDecimal(((Textbox)owner.tblFacturas.getCell(row, cols - 1)).getValue());
				}
				catch (Exception e) { }
				values.add(newValue);
			}
			// Setear valores en el modelo
			for (int row = 0; row < rows; row++) {
				((FacturasModel)owner.tblFacturas.getModel()).model.setValueAt(values.get(row), row, cols - 1);
			}
			// Invocar al metodo para actualizar toPay
			for (int row = 0; row < rows; row++) {
				ResultItemFactura rif = (ResultItemFactura)owner.getModel().m_facturas.get(row);
				int currency_ID_To = (Integer)owner.getModel().m_facturas.get(row).getItem(owner.getModel().m_facturasTableModel.getCurrencyColIdx());
				owner.getModel().actualizarPagarConPagarCurrency(row,rif,currency_ID_To);
			}
			owner.resetModel();
		}
	}
	
	/**
	 * Model para la grilla.  
	 * 
	 * Esta clase delega la estructura y lógica de determinación de los registros a recuperar al 
	 * módulo original de Ordenes de Pago, a fin de centralizar la lógica en un único lugar y
	 * simplificar ademas la complejidad de WOrdenPago.
	 */
	public static class FacturasModel extends AbstractListModel implements TableModelListener, ListModelExt {

		public TableModel model = null;
		
		public FacturasModel(TableModel model, int windowNo) {
			this.model = model;
		}

		@Override
		public Object getElementAt(int rowIndex) {
			if (model==null)
				return null;
			int columnCount = model.getColumnCount();
			Object[] values = new Object[columnCount];
			for (int i = 0; i < columnCount; i++) {
					values[i] = model.getValueAt(rowIndex, i);
				}		
			return values;
		}

		public Object getElementAt(int row, int col) {
			return model.getValueAt(row, col);
		}
		
		@Override
		public int getSize() {
			if (model==null)
				return 0;
			return model.getRowCount();
		}

		@Override
		public void sort(Comparator arg0, boolean arg1) {
			System.out.println("Sorted!");
			
		}

		@Override
		public void tableChanged(TableModelEvent e) {
			System.out.println("Changed!");		
		}	
		
		public int getColumnCount() {
			return model.getColumnCount();
		}
		
		public String getColumnName(int columnIndex) {
			return model.getColumnName(columnIndex);
		}
		
	}

	
}
