CREATE OR REPLACE VIEW RV_MPC_Product_Routing
AS
SELECT 
w.AD_Client_ID , 
w.AD_Org_ID,
w.Value,
w.Name, 
w.Description, 
w.Validfrom, 
w.ValidTo,
n.Value AS NValue,
n.Name AS NName,
n.Description AS NDescription,
r.Description AS RDescription,
r.A_Asset_ID , 
r.BatchQty,
r.C_BPartner_ID, 
r.CyclesHour,
r.MPC_StandardOperation_ID,
r.S_Resource_ID,
r.IsMilestone,
r. MoveTime,
r.NumberAsset, 
r.NumberPeople, 
r.OverlapUnits,
r.QueueTime, 
r.RunCrew,
r.RunTime,
r.SetupCrew,
r.SetupTime,
r.UnitsCycles,
r.WaitTime,
r.IsSubcontracting, 
r.ValidFrom AS RValidFrom , 
r.ValidTo AS RValidTo,
r.IsActive FROM AD_Workflow  w, AD_WF_Node n , MPC_Product_RoutingLine r WHERE w.AD_Workflow_ID = n.AD_Workflow_ID AND r.AD_WF_Node_ID = n.AD_WF_Node_ID
/
